### PR TITLE
Issue 6162: Extra spaces on Pravega.io docs -> Understanding Pravega -> Concepts

### LINKED ISSUE #6162: Extra spaces on Pravega.io docs -> Understanding Pravega -> Concepts
Initially, I was able to visually detect an extra space in the beginning of a sentence under Transaction (see #6159). However, when ctrl-f-ing the page for two spaces, I got over 30+ results that had 2 spaces at the beginning of a sentence or at the end of the sentence. To make spacing consistent, we need to remove those extra spaces.

### PR DESCRIPTION
**Pull request by kgh475926**
**Change log description**  
Removed all extra spaces in pravega-concepts.md to keep the spacing consistent among the sentences. 

**Purpose of the change**  
Fixes #6162 

**What the code does**  
N/A

**How to verify it**  
Ctrl-F for double spaces on https://pravega.io/docs/nightly/pravega-concepts/. There should be 0 results for the ctrl-f after the fix.

### CODE REVIEW

**Comment by kgh475926** [comment]
I only made changes to `pravega-concepts.md` but I'm not sure why I'm failing the Segment Store Unit Tests. Why does this happen and could I get some pointers on how to fix it?

**Comment by andreipaduroiu** [comment]
Please try it again. There are some flaky tests that fail sporadically on GHA depending on what else seems to be running there at that time. We have various issues open to address them. 

I have restarted the GHA task for you. Let's see if it works now.

**Comment by kgh475926** [comment]
@andreipaduroiu Thank you, now it has passed all checks. For future reference for myself, how can I re-run these checks on my own in case I have to restart the checks?

**Comment by andreipaduroiu** [comment]
> @andreipaduroiu Thank you, now it has passed all checks. For future reference for myself, how can I re-run these checks on my own in case I have to restart the checks?

@kgh475926 Click on `Details` next to the broken check. That will take you to the GitHub Actions portal where this is running. Somewhere on the top-right there's a button for "Re-run jobs"; clicking it (and then selecting the only sub-menu that opens) should restart the workflow. 

However I do not think that you may have permissions to do so. GH Actions only seems to show that for maintainers, so you may need to drop a comment on your PR and someone with appropriate permissions should be able to take care of that for you.

**Review by andreipaduroiu — APPROVED** [review]

**Pull request merged**
