### PR TITLE
Security system test to verify operation of a Distributed Pravega Cluster with authentication enabled.

### PR DESCRIPTION
**Pull request by pbelgundi**
**Change log description**  
Added a basic authentication test on Pravega Distributed Cluster.
See wiki for details :
 https://gist.github.com/ravisharda/5ef97136e06615776ffd95a03b669c3f

**Purpose of the change**  
This test enables authentication in Controller and Segment Store and checks if all basic operations like createScope, createStream, read/write to stream work fine with authentication enabled.
The basic 'admin' username & password provided via default password file in the controller image(/opt/pravega/conf/passwd) is used for authentication.
This test also verifies that create scope fails when incorrect username/password values are provided.

**What the code does**  
Moved the system properties set inside AbstractService.java into a separate class PravegaProperties.
These are set to their default values when authentication is not enabled, using the default builder.
Other builders can be used to get  PravegaProperties object with the right set of properties set for enabling authentication in the specific components.

These tests are run using a separate gradle task: 'startK8SystemSecurityTest' as the cluster setup (system properties) for security tests and other system tests differs and there is currently no tear down code after each test run for changing the cluster setup. 
Also, these tests have been excluded from task: 'startK8SystemTests' that runs the normal system tests.

**How to verify it**  
To verify changes, after this test run, checked options set in pravega cluster using :
'kubectl get pravegacluster pravega -o yaml'
And they had these security properties added as expected:
"controller.auth.enabled" "true"
 "controller.auth.userPasswordFile" "/opt/pravega/conf/passwd"
 "controller.auth.tokenSigningKey" "secret"
"autoScale.authEnabled" "true"
 "autoScale.tokenSigningKey" "secret"

Also checked the Controller and segment store logs for these system properties to be set at startup.
All tests in this class completed successfully.
Also performed all above checks for 'non-security' system tests and they had the right kind of properties set and completed successfully.

### CODE REVIEW

**Comment by andreipaduroiu** [comment]
@pbelgundi Here are some instructions about how to set up the DCO signoff: https://github.com/pravega/pravega/wiki/Contributing#signing-your-commits

**Comment by pbelgundi** [comment]
Hi Andrei,

I tried below command but for some reason it didn’t add the signoff…..
I have now reapplied my changes into a new branch and will raise a PR on it shortly..

-Thanks,
Prajakta

**Comment by RaulGracia** [comment]
@pbelgundi if this PR is stale and #3662 supersedes it, please close it.

**Comment by pbelgundi** [comment]
> @pbelgundi if this PR is stale and #3662 supersedes it, please close it.

Closing this PR as #3662 supersedes it.

**Pull request closed without merging**
