### PR TITLE
Issue 4149: Reduce metrics cache eviction to 3 minutes

### LINKED ISSUE #4149: Reduce Metrics Cache Eviction Timeout
**Problem description**
Before the micrometer migration, there was a problem for the traditional counter, that if the counter object was evicted from the cache, then the counter was "reset", causing the "going up and down" effect on the metrics dashboard.
To fix the problem, we had to extend the cache eviction timeout to very long, by default 30 minutes. A lot of memory is occupied by the inactive metrics objects.

Refer https://github.com/pravega/pravega/issues/886 for the discussion.

With the micrometer migration, we started using StepRegistry, and in particular, StepCounter, which nailed down the above problem completely - without changing the Counter interface to application, the StepCounter implementation is actually a Rate.
Actually @tkaitchuck already pointed it out in https://github.com/pravega/pravega/issues/886 that we should change the counter to rate. Micrometer also states there shouldn't be counter at all and they changed the underlying implementation of counter to rate, solved the problem silently and elegantly.

How exactly the problem got solved? With StepCounter, each time the counter just report the delta, without concerning the previous value. Whether the previous counter object is there or not, is no longer important.
Now It is up to the back-end to determine how to aggregate the value for the counter:  to get the traditional view of counter, just aggregate for the period "infinite past to current".
To be honest, this absolute counter value is often useless, and not practical for a streaming system (imaging the counter of total read bytes for 2 years); for streaming we usually care a particular time window or period, which the rate is designed for!

With push mode, by default we export metrics every 10 seconds. The 30 mins cache eviction is now too long and unnecessary.

**Problem location**
MetricsConfig.java - metrics.dynamicCacheEvictionDurationMinutes

**Suggestions for an improvement**
Reduce the default metrics.dynamicCacheEvictionDurationMinutes down to 3 minutes from 30 minutes.

### PR DESCRIPTION
**Pull request by kevinhan88**
Signed-off-by: kevinhan88 <kevinhan88@gmail.com>

**Change log description**  
Reduced the metrics cache eviction timeout to 3 minutes (from 30 minutes)

**Purpose of the change**  
Fixes #4149 

**What the code does**  
Changed the default cache eviction time from 30 minutes to 3 min inside MetricsConfig.java

**How to verify it**  
No functional changes.
The memory usage should be lower than before (with sufficient load) because the metrics cache now should hold less objects.

### CODE REVIEW

**Comment by fpj** [comment]
See this issue for context on why we have initially removed the TTL altogether:

     https://github.com/pravega/pravega/issues/886

and later brought it back with a much longer TTL:

    https://github.com/pravega/pravega/pull/2417

**Comment by kevinhan88** [comment]
To make things clear and straightforward, I created https://github.com/pravega/pravega/issues/4149 and assigned this pull request to that issue.

**Comment by RaulGracia** [comment]
@fpj do you mind to have another look to this PR?

**Comment by andreipaduroiu** [comment]
@kevinhan88 @fpj What's the status with this PR? Are we still pursuing it?

**Comment by kevinhan88** [comment]
@andreipaduroiu I'll have a demo tomorrow to show the difference of two approaches.

**Pull request merged**
