### PR TITLE
Issue 3440: Fix AnnotatedNoRouteToHostException observed in docker swarm based Pravega system tests.

### LINKED ISSUE #3440: Controller client's request level load balancing does not work when `AnnotatedNoRouteToHostException` is observed.
**Problem description**
The controller client request level loadbalancing does not work in case `io.grpc.StatusRuntimeException` is thrown due to `AnnotatedNoRouteToHostException`.

Details:
a. The controller client is configured with direct uri i.e. tcp://controller1:port,controller2:port,controller3:port.
b. Controller client contacts controller servers based on RoundRobin policy.
c. When the controller client talks to `controller3` it receives a `io.grpc.StatusRuntimeException` whose underlying cause is `AnnotatedNoRouteToHostException`.
In such a scenario the controller client is expected to talk to a different controller server mentioned in the  direct uri scheme, but this does not happen.
On a retry every attempt is directed to the same controller(sticky) instance which is incorrect.

Log snippet: 
```
// all the attempts were to contact controller.3.mgmqmbucklqh5rtjzk6xqe098
2019-02-28 10:02:48,538 393516 [grpc-default-executor-18] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 243543202964808 failed with server error.
2019-02-28 10:03:49,507 454485 [grpc-default-executor-39] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 243543202964808 failed with server error.
2019-02-28 10:03:52,510 457488 [grpc-default-executor-28] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 243543202964808 failed with server error.
2019-02-28 10:03:52,610 457588 [grpc-default-executor-49] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 243543202964808 failed with server error.
2019-02-28 10:03:57,927 462905 [grpc-default-executor-25] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 243543202964808 failed with server error.
2019-02-28 10:04:02,928 467906 [grpc-default-executor-25] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 243543202964808 failed with server error.
2019-02-28 10:04:07,930 472908 [grpc-default-executor-41] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 243543202964808 failed with server error.
2019-02-28 10:04:13,853 478831 [grpc-default-executor-58] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 243543202964808 failed with server error.
2019-02-28 10:04:18,854 483832 [grpc-default-executor-43] WARN  i.p.c.stream.impl.ControllerImpl - gRPC call for getEndpointForSegment with trace id 243543202964808 failed with server error.

2019-02-28 10:04:23,856 488834 [grpc-default-executor-43] WARN  i.p.c.stream.impl.ControllerImpl - getEndpointForSegment failed: 
java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE
...
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: controller.3.mgmqmbucklqh5rtjzk6xqe098.docker-network/10.0.0.14:9090
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2019-02-28 10:04:23,856 488834 [grpc-default-executor-43] TRACE i.p.c.stream.impl.ControllerImpl - LEAVE getEndpointForSegment@243543202964808 (elapsed=95623618us).   
```
Complete Log: 
[ControllerClientLogs.zip](https://github.com/pravega/pravega/files/2945279/ControllerClientLogs.zip)

**Problem location**
Controller client.

**Suggestions for an improvement**
Fix it.

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  
- Increase transaction timeout for system tests.
- Ensure segment store instances are cleaned up after MultiController test which can cause `AnnotatedNoRouteToHostException`.

**Purpose of the change**  
Fixes #3440 

**What the code does** 
- Increase the transaction timeout used by the system tests from `59` seconds to `119` seconds.
It was observed that transactions were aborted since pingTransaction grpc call to the controller took more than 2 minutes to complete during failovers.
This caused the tests to fail since the commit of aborted transaction failed. 

- Multicontroller test (it starts multiple controller instances and a single Segment store instance) reduces the controller instances to 0. This implies the `ip` of the controller used by the segment store is invalid. This can have an unintended effect on subsequent tests causing `AnnotatedNoRouteToHostException` due to stale ip. e.g: the Autoscaleprocessor residing the Segment store fails to write a scale up event since the controller ip is incorrect.
To mitigate this problem the segment store instances are stopped at the end of the test similar to the controllers.

**How to verify it**  
Docker swarm and K8s based system tests should pass.

### CODE REVIEW

**Comment by RaulGracia** [comment]
We have good and bad news from the last system test of this branch: i) the good ones is that the most complex tests have passed, so it looks that there is no instance of the problems addressed in this PR. ii) the bad one is that there are 4 test failures, all of simple tests that don't fail normally:
```
io.pravega.test.system.BookieFailoverTest.bookieFailoverTest
io.pravega.test.system.ControllerRestApiTest.restApiTests
io.pravega.test.system.MultiControllerTest.multiControllerTest
io.pravega.test.system.PravegaControllerTest.controllerTest
```

**Comment by shrids** [comment]
The other tests  failed due to a dns issue.
```
[2019-06-25T14:05:50.020Z]     com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST http://x.x.x.x:2375/images/create?fromImage=java&tag=8: 500, body: {"message":"Get https://registry-1.docker.io/v2/library/java/manifests/8: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fjava%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on x.x.x.x: server misbehaving"}
```

**Comment by RaulGracia** [comment]
Found another instance of this problem with your branch (+PR 3928). The `readTxnWriteAutoScaleWithFailoverTest` fails as follows:
1) The test failed because the scale after the second round of failovers did not happened:
```
2019-06-26 12:02:34,064 628764 [main] ERROR i.p.t.s.f.TestFrameworkException - TestFramework Exception. Type: InternalError, Details: Exception while running test method: readWriteAndAutoScaleWithFailoverTest
java.lang.AssertionError: Scaling did not happen within desired time
```
2) Looking at the Segment Store logs in the time interval for that test, we see that the `AutoScaleProcessor` actually triggered the scale event:
```
2019-06-26 11:54:07,321 181776 [auto-scaler-9] INFO  i.p.s.s.h.stat.AutoScaleProcessor - received traffic for testReadWriteAndAutoScaleScope512909515/testReadWriteAndAutoScaleStream/0.#epoch.0 with twoMinute rate = 8.781116781012077 and targetRate = 1
...
2019-06-26 11:54:07,323 181778 [auto-scaler-7] INFO  i.p.s.s.h.stat.AutoScaleProcessor - received traffic for testReadWriteAndAutoScaleScope512909515/testReadWriteAndAutoScaleStream/1.#epoch.0 with twoMinute rate = 12.333720604543656 and targetRate = 1
```
3) But it is not able to write the scale event in the internal stream:
```
2019-06-26 11:53:07,199 121654 [auto-scaler-1] WARN  i.p.s.s.h.stat.AutoScaleProcessor - Unable to create writer for requeststream: {}.
java.util.concurrent.CompletionException: java.lang.RuntimeException: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
```
4) Because the Controller service to which it tries to contact is unavailable:
```
Caused by: io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    ... 28 common frames omitted
Caused by: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
    at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
    at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
    at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
    ... 25 common frames omitted
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    at io.grpc.Status.asRuntimeException(Status.java:530)
    ... 22 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: Host is unreachable: /10.0.0.23:9090
```
This seems to be another instance of the `AnnotatedNoRouteToHostException` issue.

Questions: 
- Are we providing a set of Controllers endpoints to the `AutoScaleProcessor` so it can use any of them that is available?
- If the `AutoScaleProcessor` is not able to create the writer to `requestStream`, should we prevent the Segment Store process from starting?

**Comment by shrids** [comment]
Found the reason for having a segment store with an invalid controller ip, it was due to  `ControllerFailoverTest.java` not performing cleanup.  The test starts a segment store with a controller ip and then brings down the same controller instance. This leads to having a segment store which is configured with a non existent controller. I have updated the PR with the fix.

**Pull request merged**
