### PR TITLE
Issue 7017: Build time warnings present in build.gradle 

### LINKED ISSUE #7017: Build time warnings present in build.gradle
Description : While building Pravega, there are few build time warnings present in build.gradle due to the usage of deprecated properties and configurations.

Location : The warnings are from build.gradle

Suggestions :
- Changing Runtime configuration to RuntimeOnly.
- Changing AbstractArchiveTask.archiveName property to archieveFileName.
- Changing AbstractArchiveTask.destinationDir property to destinationDirectory.
- Changing AbstractArchiveTask.extension property to archieveExtension.
- Changing Distribution.baseName property to distributionBaseName.
- Changing runtime configuration to runtimeClasspath.

### PR DESCRIPTION
**Pull request by PrajnaU**
**Change log description**
Handling Build time warnings which were caused due to the usage of deprecated properties and configurations in build.gradle.

**Purpose of the change**
Fixes #7017  

**What the code does**
There were 13 warnings from build.gradle and were handled by
Changing Runtime configuration to RuntimeOnly.
Changing AbstractArchiveTask.archiveName property to archieveFileName.
Changing AbstractArchiveTask.destinationDir property to destinationDirectory.
Changing AbstractArchiveTask.extension property to archieveExtension.
Changing Distribution.baseName property to distributionBaseName.
Changing runtime configuration to runtimeClasspath.

**How to verify it**
There should be no build time warnings from build.gradle

### CODE REVIEW

**Comment by shshashwat** [comment]
Please run the system tests and share the build number

**Comment by PrajnaU** [comment]
Ran the system tests and it succeeded .

**Review by Bhupender-Y — APPROVED** [review]
Please update your branch with master.

**Review by anju-c-das — APPROVED** [review]
LGTM

**Review by ShwethaSNayak — APPROVED** [review]
LGTM

**Pull request merged**
