### PR TITLE
Issue 4775: (R0.8) Cherry-pick #4776

### LINKED ISSUE #4775: Add snapshot stage for all release branches
**Problem description**
For doing a release candidate or bugfix for `0.7.1` downstream projects like the connectors, it is hard to pick up the latest `0.7.1` Pravega client dependency directly from the [jfrog](http://oss.jfrog.org/jfrog-dependencies/io/pravega/pravega-client/).

This is because https://github.com/pravega/pravega/blob/master/.travis.yml#L37 this line is checking only master branch and doing snapshot packaging.

**Problem location**
`.travis.yml`

**Suggestions for an improvement**
Add all release branches `r0.*` in that check to let the connector pick the dependency.
Similar with what is done in Flink connector:  https://github.com/pravega/flink-connectors/blob/master/.travis.yml#L39

### PR DESCRIPTION
**Pull request by crazyzhou**
Signed-off-by: Brian Zhou <brian.zhou@emc.com>

**Change log description**  
Cherrypick #4776 into 0.8

- Issue 4775: Add snapshot stage for all release branches

**Purpose of the change**  
Fixes #4775 
This will benefit to have `0.8.1-SNAPSHOT` artifacts.

**What the code does**  
Cherrypick #4776 into 0.8

**How to verify it** 
Build passes

### CODE REVIEW

**Comment by crazyzhou** [comment]
Note this change violates the [current release process](https://github.com/pravega/pravega/wiki/How-to-release) , because we now remove `-SNAPSHOT` from the version early in the release cycle and the travis build will fail on the publish stage with a non-SNAPSHOT version.

For the new release process, I would suggest we follow other Apache projects such as Apache zookeeper. Like this: https://github.com/apache/zookeeper/commit/803c7f1a12f85978cb049af5e4ef23bd8b688715
We only remove `-SNAPSHOT` from the version each time we start a release candidate or a formal release, and this commit will just be tagged but not go into the release branch. Only in this case, we can guarantee this change will not break the travis build.

**Comment by medvedevigorek** [comment]
I don't think we should take this change as is, we know it's going to break Travis builds once we enter RC phase. And looks to me that adjusting the release process alone may not be the desired solution to that. I've started a discussion in [#release-process](https://pravega-io.slack.com/archives/C01CFQ9556F ) Slack channel., let's see if we can find a solution.

**Review by ravisharda — APPROVED** [review]

**Comment by ravisharda** [comment]
@medvedevigorek regarding your comments below, with the recent discussion in Slack are you OK with having this change in now? Please confirm, so that we can unblock this PR. 

> I don't think we should take this change as is, we know it's going to break Travis builds once we enter RC phase. And looks to me that adjusting the release process alone may not be the desired solution to that. I've started a discussion in #release-process Slack channel., let's see if we can find a solution.

**Comment by crazyzhou** [comment]
Close this to cherrypick the correct commit and keep a cleaner history

**Pull request closed without merging**
