### PR TITLE
Issue 1293: Update Marathon Group

### LINKED ISSUE #1293: Marathon group should pull official docker images
**Problem description**
The current `PravegaGroup.json` file points to old docker images. We should use the official images from `/pravega/pravega`.  The existing group is also pointing to the zookeeper at `master.mesos`, which in most cases will be a version 3.4.X. I believe we depend on 3.5.X.

**Problem location**
https://github.com/pravega/pravega/blob/master/PravegaGroup.json

**Suggestions for an improvement**
I'll have a PR up to fix this very shortly.

### PR DESCRIPTION
**Pull request by dsrw**
**Change log description**
This updates our marathon group to pull the official docker images, add ZooKeeper and HDFS to the deploy, moves everything to `docker/marathon`, and adds a very simple README.

**Purpose of the change**
The current `PravegaGroup.json` is outdated, and likely doesn't work. We should either remove it or update it. This PR updates it.

**What the code does**
This updates the marathon group to more or less match the docker-compose and docker swarm deployments.

**How to verify it**
See the included `Readme.md` for deployment instructions.

Fixes #1293

### CODE REVIEW

**Comment by Prabha-Veerubhotla** [comment]
System tests are not deployed using PravegaGroup.json.  As, Arvind mentioned, no one is using PravegaGroup.json now.

**Comment by Prabha-Veerubhotla** [comment]
The updated json seems to miss  the `group` structure and is posting to `/v2/groups`. How does it work ?

**Comment by dsrw** [comment]
Closing in favor of #1321. I lost my branch when Pravega went public.

**Comment by dsrw** [comment]
Closing in favor of #1321. I lost my branch when Pravega went public.

**Pull request closed without merging**
