### PR TITLE
Issue 6278: Add missing jq tool

### LINKED ISSUE #6278: Include missing tools into the docker image
**Describe the bug**
Pravega startup scripts query some K8s objects and filter the output using `jq` tool. The tool is actually missing since moving to the alpine based docker image which causes the startup scripts to fail. 

It actually happens when External Access is enabled as then the startup scripts need to check the presence of corresponding K8s service before starting up Pravega services 

**To Reproduce**
Deploy Pravega docker image in K8s environment with Pravega External Access enabled 

**Screenshots**
None

**Additional information**
The actual logic that depends on `jq` tool is [here](https://github.com/pravega/pravega/blob/master/docker/pravega/scripts/init_kubernetes.sh#L26)

### PR DESCRIPTION
**Pull request by medvedevigorek**
Signed-off-by: Igor Medvedev <medvedevigorek@gmail.com>

**Change log description**  
Added installation of `jq` tool 

**Purpose of the change**  
Fixes #6278 

**What the code does**  
Modified Pravega Dockerfile to include installation of `jq` tool on top of the base image 

**How to verify it**  
Run the docker image in K8s environment and have External Access enabled

### CODE REVIEW

**Review by gaddamas — COMMENTED** [review]
you need the following change as well
```
diff --git a/docker/pravega/scripts/init_kubernetes.sh b/docker/pravega/scripts/init_kubernetes.sh
index 3f481f267..def802ec7 100755
--- a/docker/pravega/scripts/init_kubernetes.sh
+++ b/docker/pravega/scripts/init_kubernetes.sh
@@ -55,10 +55,11 @@ init_kubernetes() {
         export PUBLISHED_PORT=""
         local service=$( k8 "${ns}" "services" "${podname}" .kind )

-        if [[  "$service" != "Service" ]];
-        then
+        if [[  "${service}" != "Service" ]]; then
             echo "Failed to get External Service. Exiting..."
-            exit 1
+            exit 1
+        else
+            echo "Found SegmentStore Service"
         fi
```

**Comment by medvedevigorek** [comment]
> you need the following change as well
> 
> ```
> diff --git a/docker/pravega/scripts/init_kubernetes.sh b/docker/pravega/scripts/init_kubernetes.sh
> index 3f481f267..def802ec7 100755
> --- a/docker/pravega/scripts/init_kubernetes.sh
> +++ b/docker/pravega/scripts/init_kubernetes.sh
> @@ -55,10 +55,11 @@ init_kubernetes() {
>          export PUBLISHED_PORT=""
>          local service=$( k8 "${ns}" "services" "${podname}" .kind )
> 
> -        if [[  "$service" != "Service" ]];
> +        if [[  "${service}" != "Service" ]];
> ```

@gaddamas Why is it needed? What else has changed since moving to Alpine that requires this additional change?

**Comment by gaddamas** [comment]
> > you need the following change as well
> > ```
> > diff --git a/docker/pravega/scripts/init_kubernetes.sh b/docker/pravega/scripts/init_kubernetes.sh
> > index 3f481f267..def802ec7 100755
> > --- a/docker/pravega/scripts/init_kubernetes.sh
> > +++ b/docker/pravega/scripts/init_kubernetes.sh
> > @@ -55,10 +55,11 @@ init_kubernetes() {
> >          export PUBLISHED_PORT=""
> >          local service=$( k8 "${ns}" "services" "${podname}" .kind )
> > 
> > -        if [[  "$service" != "Service" ]];
> > +        if [[  "${service}" != "Service" ]];
> > ```
> 
> @gaddamas Why is it needed? What else has changed since moving to Alpine that requires this additional change?

could be shell is different, while testing I see it was not matching

**Review by anishakj — APPROVED** [review]
LGTM

**Review by RaulGracia — APPROVED** [review]

**Pull request merged**
