### PR TITLE
Issue 522: Add error handling JVM options

### PR DESCRIPTION
**Pull request by giorgio-v**
This PR is my first stab at this project. I’ve simply verified launching with `docker compose`. Assuming the proposed changes make sense, I’d like to know what should be done to test it more throughly.

HTH

**Change log description**
Add the following JVM flags
 - `-XX:OnError="kill -9 p%"`
 - `-XX:+HeapDumpOnOutOfMemoryError`
 - `-XX:+ExitOnOutOfMemoryError`
 - `-XX:+CrashOnOutOfMemoryError`

and reformat to avoid long lines.

_The last two options were added with JDK 8u92_

**Purpose of the change**
Address  #522 

**What the code does**
Kills the JVM process on unrecoverable errors.

**How to verify it**
TBD

### CODE REVIEW

**Comment by fpj** [comment]
@giorgio-v thanks a lot for your contribution! we are currently in the process of figuring out the DCO vs. CLA stuff so that we can accept contributions from the community, which should be resolved shortly. please bear with us.

**Comment by giorgio-v** [comment]
@fpj 👍

**Comment by fpj** [comment]
@giorgio-v thank you for your patience. could you please follow the instructions here to sign-off your commits so that we can get it merged?

https://github.com/pravega/pravega/wiki/Contributing#dco

**Comment by giorgio-v** [comment]
@fpj Done. 😃Thanks for getting back to me.

**Pull request merged**
