### PR TITLE
Issue 4938: Merge branch 'master' into feature-4938-dr-tools-base-case

### PR DESCRIPTION
**Pull request by ManishKumarKeshri**
**Change log description**  
Updates the feature branch with the changes from the latest master.

**How to verify it**  
Build shall pass.

### CODE REVIEW

**Review by sachin-j-joshi — APPROVED** [review]
LGTM. Waiting on build to complete.

**Comment by sachin-j-joshi** [comment]
@fpj Need your help in merging this change with a merge commit.
The target here is a feature branch and this change pulls master into it. We do not want to squash the commits.
Thanks

**Comment by sachin-j-joshi** [comment]
waiting on build to complete.

**Comment by ManishKumarKeshri** [comment]
@fpj & @sachin-j-joshi. Build is complete.

**Pull request merged**
