### PR TITLE
Issue 5448: Deprecate existing DefaultCredentials in favor of a new one placed in a more appropriate location

### LINKED ISSUE #5448: The location of `DefaultCredentials` class is awkward
**Problem description**
Currently, the `DefaultCredentials` class lies in the `io.pravega.client.stream.impl` package. The `stream` and the `impl` parts are somewhat awkward: 
- This class' usage is not limited to just the event stream API. 
- The term `impl` is (arguably) tautological. 

A more appropriate location of the class may be `io.pravega.shared.security.auth` in the `:shared:security` Gradle module. 

`r0.9` has moved several security classes around for reuse and easier consumption as part of PRs #5339, #5436 and #5373. Those changes include deprecation of the old `io.pravega.client.stream.impl.Credentials` interface  in favor of `io.pravega.shared.security.auth.Credentials`, The older `Credentials` interface shall be removed in a later release (issue #5383). Why not move the `DefaultCredentials` implementation too, so that users will need to deal with migrating these two together in one go?

cc/ @fpj, @medvedevigorek and @crazyzhou

**Problem location**

**Suggestions for an improvement**
Deprecate the preexisting `DefaultCredentials` class and introduce a new one in a more appropriate location.

### PR DESCRIPTION
**Pull request by ravisharda**
**Change log description**  
Deprecates existing default crendentials class `io.pravega.client.stream.impl.DefaultCredentials` in favor of `io.pravega.shared.security.auth.DefaultCredentials`.

**Purpose of the change**  
Fixes #5448

**What the code does**  
Deprecates existing default crendentials class `io.pravega.client.stream.impl.DefaultCredentials` in favor of `io.pravega.shared.security.auth.DefaultCredentials`.

Here's a UML diagram that shows how the new and old interface/implementations are related: 

image

**How to verify it**  
All unit, integration, and system tests must pass.

### CODE REVIEW

**Comment by ravisharda** [comment]
Started a system test run via branch builder run 643.

**Review by crazyzhou — APPROVED** [review]
LGTM. If I understand correctly, this is what you did:
credentials

**Comment by ravisharda** [comment]
> LGTM. If I understand correctly, this is what you did:
> credentials

Thanks, @crazyzhou. The relationships shown in your diagram are correct. In addition, the old `io.pravega.client.stream.impl.DefaultCredentials` uses `io.pravega.shared.security.auth.DefaultCredentials` to do the work. Borrowing from your depiction, I've now added a new UML diagram in the description that shows those relationships.

**Review by shrids — APPROVED** [review]
LGTM.

**Review by medvedevigorek — APPROVED** [review]

**Review by fpj — COMMENTED** [review]
+1

**Pull request merged**
