### PR TITLE
Issue 6850: Adding Java doc for fetchStreamInfo API

### PR DESCRIPTION
**Pull request by ShwethaSNayak**
Signed-off-by: Shwetha N <shwetha.n1@dell.com>

**Change log description**  
Updating Java docs for fetchStreamInfo() API.

**Purpose of the change**  
#6850 

**What the code does**  
Updating Java docs for fetchStreamInfo() API.

**How to verify it**  
All tests should pass

### CODE REVIEW

**Review by crazyzhou — APPROVED** [review]
LGTM

**Review by shshashwat — APPROVED** [review]
LGTM

**Review by kotlasaicharanreddy — APPROVED** [review]
LGTM.

**Review by RaulGracia — APPROVED** [review]

**Comment by RaulGracia** [comment]
@ShwethaSNayak is the "Change log description" describing what this PR is doing? Is just a javadoc change, right?

**Pull request merged**
