### PR TITLE
Draft PR for experiment, Issue 3900: Disable connection pooling

### PR DESCRIPTION
**Pull request by tkaitchuck**
Signed-off-by: Tom Kaitchuck <tom.kaitchuck@emc.com>

**Change log description**  
Disable connection pooling.

**Purpose of the change**  
Experiment to see if pooling is related to #3900 

**What the code does**  
Disables pooling

**How to verify it**  
Run tests. 

DO NOT MERGE

### CODE REVIEW

**Comment by shrids** [comment]
This disables connection pooling only for the SegmentMetaClient and StateSynchronizer.
Connection pooling is still enabled for append and read paths.

**Comment by andreipaduroiu** [comment]
@tkaitchuck Is this PR still needed? I believe we've resolved issue 3900.

**Comment by fpj** [comment]
@andreipaduroiu this is actually not for #3900, but to address the performance penalty that connection pooling has introduced. I'd like to have it so that we can turn it off in the case the performance hit due to connection pooling becomes a problem.

**Comment by andreipaduroiu** [comment]
Ok, understood. Can we change the title to something that is more appropriate and that doesn't reference isuse 3900?

**Comment by fpj** [comment]
I got confused with PR #3952 , we can close this one.

**Pull request closed without merging**
