### PR TITLE
Issue 6159: Extra space on Pravega.io docs -> Understanding Pravega -> Concepts -> Transactions

### LINKED ISSUE #6159: Extra space on Pravega.io docs -> Understanding Pravega -> Concepts -> Transactions
**Problem description and location**
While reading the docs on Pravega.io docs -> Understanding Pravega -> Concepts -> Transactions, I found an extra space in the beginning of the last sentence of the second paragraph.

**Suggestions for an improvement**
Delete the extra space in the beginning of the sentence.

### PR DESCRIPTION
**Pull request by kgh475926**
**Change log description**  
Removed an extra space in pravega.concepts.md.

**Purpose of the change**  
Nitpick. Fixes #6159 

**What the code does**  
N/A

**How to verify it**  
Visually see the changes.

### CODE REVIEW

**Comment by andreipaduroiu** [comment]
Hi @kgh475926 ! Thank you for your contribution! We always welcome any change, no matter how small, that improves our codebase or documentation.

I have a small "nitpick" on your nitpick :) In the `Purpose of the change` section, please refer to the GitHub issue that this PR is resolving. For example, `Fixes #6159` is what we usually put there - that way, when we merge this PR, GitHub will automatically close the referenced issue.

Thanks!

**Comment by kgh475926** [comment]
Thank you for the guideline! I'll keep that in mind for subsequent works.

**Review by andreipaduroiu — APPROVED** [review]

**Comment by andreipaduroiu** [comment]
@kgh475926 Can you please resolve your merge conflicts on this PR? I got this when I merged one of your other PRs.

**Comment by kgh475926** [comment]
@andreipaduroiu I resolved the conflict. Could you take a look again?

**Comment by kgh475926** [comment]
Could I get a re-run on the GHA checks? (All Oher Unit Tests is failing).

**Pull request merged**
