### PR TITLE
Issue 5638: System test fail fast

### LINKED ISSUE #5638: System test fail fast
**Problem description**
System test should fail fast instead of running to the end when there is an error. This way it can save a lot of time running the test.

**Problem location**
system test

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by Tristan1900**
**Change log description**  
Add support for configurable system test fail fast.
User can pass argument `./gradlew startK8SystemTests -DfailFast = true` to enable this feature.
 
**Purpose of the change**  
Fix #5638 

**What the code does**  
Add fail fast option to the gradle 

**How to verify it**  
Has been verfied in Jenkins job

### CODE REVIEW

**Comment by RaulGracia** [comment]
@Tristan1900 You have tested the behavior if this, right? Can the "fail fast" behavior be configurable? That is, would it make sense to have it as an option when running system tests? A `--failFast` flag or similar may be interesting when executing system tests, so we can manipulate it from a Jenkins job, for instance.

**Comment by Tristan1900** [comment]
Thanks @RaulGracia, I have verified that this change works in my Jenkins job. I'm also making the change to Jenkins repo now.

**Review by ManishKumarKeshri — APPROVED** [review]

**Review by shrids — APPROVED** [review]
LGTM.

**Review by RaulGracia — APPROVED** [review]

**Comment by Tristan1900** [comment]
Hey @co-jo, could you take a look at this PR and see if it looks good to you? Thanks.

**Comment by co-jo** [comment]
LGTM.

**Review by co-jo — COMMENTED** [review]
LGTM.

**Review by co-jo — CHANGES_REQUESTED** [review]
LGTM

**Review by co-jo — APPROVED** [review]
LGTM (Third time is the charm).

**Pull request merged**
