### PR TITLE
Issue 3570: Reduce recursive call to ZKOrderedStore#addEntity

### LINKED ISSUE #3570: Use Zookeeper transactions in ZkOrdered Store to atomically update using new collection
**Problem description**
Based on suggestion here, 
https://github.com/pravega/pravega/pull/3419/files#r272519127
we could use transaction support from zookeeper in zk ordered store. 

**Problem location**
zk ordered store

**Suggestions for an improvement**
Use zookeeper transactions.

### PR DESCRIPTION
**Pull request by TisonKun**
Signed-off-by: tison <wander4096@gmail.com>

**Change log description**  

Flatten the recursive call to `ZKOrderedStore#addEntity` for readability.

**Purpose of the change**  

Closes #3570 

**What the code does**  

Flatten the recursive call to `ZKOrderedStore#addEntity` for readability. A known risk is that it is theoretically possible that we exhaust new collection before add the new entity but it is almost theoretically only(I think in production, we always roll over after about 1.8 billion).

**How to verify it**  

Existing tests should guard we don't change the behavior. This change itself is a trivial refactor that doesn't deserve a dedicate test.(And the only difference to current codebase is a theoretical failure that is hard to reproduce and can be safely ignored.)

cc @shiveshr @fpj

### CODE REVIEW

**Comment by TisonKun** [comment]
Thanks for your review @shiveshr!

Travis fails on 

> io.pravega.test.integration.ControllerGrpcListStreamsTest > testListStreamsReturnsAuthorizedStreamsOnly FAILED
>     java.lang.RuntimeException: java.lang.IllegalStateException: Expected the service ControllerServiceStarter [FAILED] to be RUNNING, but the service has FAILED
>         at io.pravega.test.integration.demo.ClusterWrapper.initialize(ClusterWrapper.java:110)
>         at io.pravega.test.integration.ControllerGrpcListStreamsTest.testListStreamsReturnsAuthorizedStreamsOnly(ControllerGrpcListStreamsTest.java:106)
> 
>         Caused by:
>         java.lang.IllegalStateException: Expected the service ControllerServiceStarter [FAILED] to be RUNNING, but the service has FAILED
>             at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:366)
>             at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:302)
>             at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:165)
>             at io.pravega.test.integration.demo.ControllerWrapper.awaitRunning(ControllerWrapper.java:177)
>             at io.pravega.test.integration.demo.ClusterWrapper.startController(ClusterWrapper.java:122)
>             at io.pravega.test.integration.demo.ClusterWrapper.initialize(ClusterWrapper.java:107)
>             ... 1 more
> 
>             Caused by:
>             java.lang.IllegalStateException: Expected the service GRPCServer [FAILED] to be RUNNING, but the service has FAILED
> 
>                 Caused by:
>                 java.io.IOException: Failed to bind
> 
>                     Caused by:
>                     java.net.BindException: Address already in use

I guess it is because an unstable tests worth a ticket and is unrelated to this patch.

**Comment by TisonKun** [comment]
So how to re-trigger CI? I don't want to close and reopen though.

**Comment by shiveshr** [comment]
click on "Details" link (https://travis-ci.org/pravega/pravega/builds/590525798?utm_source=github_status&utm_medium=notification) against the travis build and restart the build. 
I have restarted the build for you

**Comment by TisonKun** [comment]
Thanks for your information and help @shiveshr!

**Comment by TisonKun** [comment]
Thank @shiveshr for the review!

**Pull request merged**
