### PR TITLE
Issue 6966: Add missing admin cli argument documentation for DurableLogInspectCommand

### LINKED ISSUE #6966: Update missing argument for DurableLogInspectCommand
**Describe the bug**
Add missing argument for DurableLogInspectCommand. 

**To Reproduce**
While using the admin cli and executing `data-recovery durableLog-inspect <container-id>`  , the fourth argument i.e <filename> is missing in the documentation of the command.

**Screenshots**
N/A

**Additional information**
N/A

### PR DESCRIPTION
**Pull request by kuldeepk3**
Adding missing admin cli documentation for missing argument for DurableLogInspectCommand.

Signed-off-by: Kuldeep Kumar <kuldeep.kumar3@dell.com>

**Change log description**  
Adding the missing admin cli argument for DurableLogInspectCommand which landed user into errors given below
`Bad command syntax: Incorrect argument count.
        data-recovery durableLog-inspect <container-id>: Allows to inspect DurableLog damaged/corrupted Operations.
                <container-id>: Id of the Container to inspect.`

**Purpose of the change**  
fixes #6966

**What the code does**  
Adding missing admin cli argument for DurableLogInspectCommand

**How to verify it**  
Execute the DurableLogInspectCommand

### CODE REVIEW

**Comment by kuldeepk3** [comment]
Sure @RaulGracia , I also think that it will be good to have a test for it, will check and update.

**Comment by abhinb** [comment]
@kuldeepk3 
are we planning to add the generic test discussed above as part of this PR? If not we can merge this and create a issue for the generic test case.

**Comment by kuldeepk3** [comment]
Hi @abhinb , we can merge this pr.

**Review by ShwethaSNayak — APPROVED** [review]
LGTM, @kuldeepk3, are you adding test for validating number of input arguments as suggested by Raul?

**Comment by kuldeepk3** [comment]
> LGTM, @kuldeepk3, are you adding test for validating number of input arguments as suggested by Raul?

Hi Shwetha, will add generic test in different pr.

**Pull request merged**
