### PR TITLE
Issue 1293: Update Marathon Group

### LINKED ISSUE #1293: Marathon group should pull official docker images
**Problem description**
The current `PravegaGroup.json` file points to old docker images. We should use the official images from `/pravega/pravega`.  The existing group is also pointing to the zookeeper at `master.mesos`, which in most cases will be a version 3.4.X. I believe we depend on 3.5.X.

**Problem location**
https://github.com/pravega/pravega/blob/master/PravegaGroup.json

**Suggestions for an improvement**
I'll have a PR up to fix this very shortly.

### PR DESCRIPTION
**Pull request by dsrw**
**Change log description**
This updates our marathon group to pull the official docker images, add ZooKeeper and HDFS to the deploy, moves everything to `docker/marathon`, and adds a very simple README.

**Purpose of the change**
The current `PravegaGroup.json` is outdated, and likely doesn't work. We should either remove it or update it. This PR updates it.

**What the code does**
This updates the marathon group to more or less match the docker-compose and docker swarm deployments.

**How to verify it**
See the included `Readme.md` for deployment instructions.

Fixes #1293

### CODE REVIEW

**Comment by dsrw** [comment]
@Prabha-Veerubhotla responding to your question from #1294.

A marathon group can just be a collection of apps. It doesn't require subgroups. This group does deploy and run in DC/OS using the instructions in `Readme.md`.

**Comment by dsrw** [comment]
@arvindkandhare responding to your question from #1294.

This is meant to provide a quick and easy DC/OS deployment options for users. @maddisondavid is working on a DC/OS framework that would make this obsolete, but it's unclear right now when or if it will be publicly released.

That said, I'm fine with deleting this if that's the way the team wants to go.

**Comment by fpj** [comment]
I wanted to make progress with this pull request. There is this comment in the description:
```
The current PravegaGroup.json is outdated, and likely doesn't work. We should either remove it or update it. 
```

What's the recommendation here, update or remove? Who is using or going to use this marathon deployment?

**Comment by dsrw** [comment]
I don't think anyone on our team will use this. This is for end users looking to deploy on DC/OS or Marathon. I'm fine with throwing it out until someone asks for it.

**Comment by dsrw** [comment]
Closing for now. We can add this later if there's a need.

**Pull request closed without merging**
