### PR TITLE
Issue 1142 : Implement a shaded in-proc Pravega cluster

### LINKED ISSUE #1142: Implement a shaded in-proc Pravega cluster
**Problem Description**
The work of #573 provides an in-process Pravega cluster (`LocalPravegaEmulator`) for use in client-side integration tests.   Dependency conflicts are likely to happen in such an environment, for example when writing Flink connector tests that use Flink's in-process cluster.

A solution to the conflict is to build a shaded JAR of the Pravega emulator that isolates most of Pravega's dependencies.   Ideally the library would leave only `io.pravega.*` unshaded.

**Suggested Fix**
I suggest the overall dependency tree be (as seen from the app perspective, with shaded deps elided):

```
flink-job
├─ flink-streaming-java (provided)
├─ pravega-connector (compile)
│  └─ pravega-client (compile)
└─ pravega-standalone (intTest)
   └─ pravega-client (compile)
```

To achieve the above, most of the shading work that is presently done in the connector should move to the client library.

### PR DESCRIPTION
**Pull request by sachin-j-joshi**
**Change log description**  
Build a shaded JAR that isolates LocalPravegaEmulator dependencies.

**Purpose of the change**  
Fixes #1142 Implement a shaded in-proc Pravega cluster

**What the code does**  
Modify jar task for standalone project to include dependencies and create a 'fat'jar.
Modify startStandalone task to launch fat jar instead of providing dependencies on classpath

**How to verify it**  
The task :standalone:startStandalone should start normally as before and work without any class load exceptions.

### CODE REVIEW

**Comment by sachin-j-joshi** [comment]
Thanks a lot @EronWright and @adrianmo. Working on the fix/changes.

**Comment by EronWright** [comment]
@fpj and @sachin-j-joshi, consider re-opening #1339 to tackle shading the pravega client as the first logical step to realize the arrangement that I suggested in #1142 description.

**Comment by sachin-j-joshi** [comment]
@EronWright I pushed the change as you suggested. Not sure if this direction is what you have in mind. 
@adrianmo I'm still testing my changes.

**Comment by sachin-j-joshi** [comment]
quick update - I ran into the issue with ./gradlew install with this approach. 

Execution failed for task ':standalone:install'.
> Could not publish configuration 'archives'
   > A POM cannot have multiple artifacts with the same type and classifier. Already have MavenArtifact pravega-standalone:zip:zip:null, trying to add MavenArtifact pravega-standalone:zip:zip:null.

**Comment by sachin-j-joshi** [comment]
@EronWright We are still waiting on deciding next steps for [#1339](https://github.com/pravega/pravega/issues/1339) . In the meantime, I think we should go ahead with this current change. 
Based on your previous comments, I have made changes and now it produces shaded jar, not just the fat jar.

**Comment by EronWright** [comment]
@sachin-j-joshi I would like to approve this but would you kindly confirm that the contents of the shaded JAR are purely `io.pravega` (incl `io.pravega.shaded...`) ?

**Comment by ravisharda** [comment]
@sachin-j-joshi Just realized that this change also makes it possible to run Pravega standalone on a Windows host, which is great (although, I prefer to run it on Linux). 

Previously, on Windows the ``startStandalone`` Gradle task'd error out with a message like: ``Createprocess error=206; the filename or extension is too long``, and this was because the number of characters passed to Windows CreateProcess exceeded the max limit owing to the lengthy classpath entries. With this change, the ``startStandalone`` task runs successfully.

**Comment by sachin-j-joshi** [comment]
@EronWright Thanks. Currently the final jar produced has lot more than just pravega and relocated bits. 

I'm working on changes so that the content of the jar are purely pravega + relocated packages. Because of transitive nature of how jars are included, I'm not precisely able to control what goes into the final jar. (It seems I can control the dependencies to include by explicitly including them or excluding them). 

One side effect is that we have to provide all other jars on the classpath while running standalone. (not single jar anymore).  I am assuming this is what we want.

This change is taking a bit longer than expected.

**Comment by andreipaduroiu** [comment]
@sachin-j-joshi @EronWright What is the status of this? I haven't seen any activity in almost 2 months.

**Comment by sachin-j-joshi** [comment]
This change needs to be re-thought, re-prioritized and re-done.
Closing for now.

**Pull request closed without merging**
