### PR TITLE
Issue 7245: System test to validate Segment based reader APIs.

### PR DESCRIPTION
**Pull request by amit-kumar59**
Change log description.
Spark is using the Pravega API using below steps.
Read limit feature is being used by creating a micro batch and reading the events in a batch.

Respectively, there are system test case for scale up and down for the next stream cut.
System test 1: Get next stream cut with scale up.
System test 2: Get next stream cut with scale Down.

Purpose of the change
fixes https://github.com/pravega/pravega/issues/7245

What the code does
System test 1: Get next stream cut with scale up.
Here, there are multiple streams cut by calling getStreamCut function, read the data between the streams cut validate as well and at last perform the scale up and validate it accordingly.

System test 2: Get next stream cut with scale Down.
Here, performs the scale up and validate it and performing the scale down and validating it.

How to verify it
Run the system test and All test should work fine.

### CODE REVIEW

**Review by Bhupender-Y — CHANGES_REQUESTED** [review]
Please update the PR title. Usually we follow https://github.com/pravega/pravega/wiki/Contributing#creating-a-pull-request. Also it will be good if you can mention some detail about getNextStreamCut API instead of explaining about spark use case in change log description.

**Review by tkaitchuck — APPROVED** [review]

**Comment by amit-kumar59** [comment]
> Please update the PR title. Usually we follow https://github.com/pravega/pravega/wiki/Contributing#creating-a-pull-request

added

**Review by Bhupender-Y — APPROVED** [review]
LGTM

**Review by munish1789 — APPROVED** [review]
LGTM

**Comment by ShwethaSNayak** [comment]
@amit-kumar59 Add the reference of successful system test run.

**Comment by amit-kumar59** [comment]
System Test Ref
Job: mk-pravega-system-test
Id : 51

**Comment by ShwethaSNayak** [comment]
> System Test Ref Job: mk-pravega-system-test Id : 51

Here I see a newly added system test been executed, can you please run entire system test suit on this code base and share the details.

**Review by anju-c-das — COMMENTED** [review]
LGTM

**Review by anju-c-das — APPROVED** [review]

**Comment by amit-kumar59** [comment]
https://github.com/pravega/pravega/pull/7275#issuecomment-1731239858
Run the entire system test.
System Test Ref
Job: mk-pravega-system-test
Id: 52

**Pull request merged**
