### PR TITLE
Issue 7346: miniBenchark Integration test failing on Github Action

### LINKED ISSUE #7346: miniBenchmark append test failing on GithubActions
**Describe the bug**
AppendTest.miniBenchMark has been failing consistently on GitHub Actions lately whereas passing on internal build machines; when there hasnt been any code changes on the append path that can fail the benchmark.

**To Reproduce**
miniBenchark Integration test fails on raising PR's on master.

**Screenshots**

**Additional information**

### PR DESCRIPTION
**Pull request by abhinb**
**Change log description**  
Increases resources for the gradle daemon process that runs the tests. 

**Purpose of the change**  
Fixes #7346.

**What the code does**  
The integration test has been failing consistently ONLY on Github Actions. The sudden failure could be related to some change(possibly low resource Github Action Runners assigned?) in Github Action infra. miniBenchark Append Integration test just does a thousands of blocking and non blocking appends and expects the appends to be through within a certain reasonable time. This PR merely increases the resources for the gradle daemon process that runs the tests.

While more effort needs to go into finding out if there has been any change on the Github Action Runner side or any other aspect that could possibly fail the test consistently, which could be an ongoing effort,  as it stands this PR should help unblock PR merges on master branch.

**How to verify it**  
PR's raised on GH not failing due to miniBenchark Append Integration test failing.

### CODE REVIEW

**Review by RaulGracia — APPROVED** [review]

**Review by tkaitchuck — CHANGES_REQUESTED** [review]
Temporarily blocking.

Looking at some of the failures, it seems odd to me in that it is sometimes timing out, implying that it didn't merely take more than 10s to complete the blocking calls but more than 20s. But reducing it from 3000 to 2400 brings it from 20s to under 10. Something strange is going on.

**Comment by tkaitchuck** [comment]
It may be useful to debug this with a test PR against master and the release branches which uncomments this:
https://github.com/pravega/pravega/blob/master/.github/workflows/gradle.yml#L101
to get a debug session and then connecting and running:
`./gradlew test:integration:test --rerun-tasks -i --tests '*AppendTest.miniBenchmark'`
So that we can see the actual timing information with different values of appends against different versions of the code.

**Comment by abhinb** [comment]
@tkaitchuck 
Observations via the upterm session on GitHub Runners:

- 	GitHub Runners assigned have 4 CPU with 16GB RAM.

- 	Individual minibenchmark test always passes with  approx below numbers on multiple branches( master, 0.12):

 

> Blocking took: 2392ms.                                                                                                                                                                                                                                 
> Non blocking took: 844ms


- 	However when we run the whole set of integration tests minibenchmark has always failed out of the 2-3 runs done on multiple branches(master, 0.12)

- 	Since its also failing on old branch like 0.12, and always passes as an inidividual test across branches, it seemed more like a resource issue, so tried increasing   the heap associated with gradle, and also configured the max gradle workers, which based on the documentation helps utilize the available CPU cores in multi-project gradle build/test executions.

 
-   The above config change resulted in integration tests passing consistently for the 2-3 runs executed on master and 0.12 branches on _the Github Runners via the UPTERM session_.

**Comment by abhinb** [comment]
@tkaitchuck 
Can we consider/merge this change as its given consistent green runs inside the Github VM's while testing this change.

**Review by tkaitchuck — APPROVED** [review]

**Pull request merged**
