### PR TITLE
Issue 6803: Fix standalone log location prompt

### LINKED ISSUE #6803: Standalone log location prompt is wrong
**Describe the bug**
The log prints
```
log.info("For more detailed logs, see: {}/{}", System.getProperty("user.dir"), "standalone.log");
```
But acutally, there is no standalone directory.
Also see the logback config file: https://github.com/pravega/pravega/blob/4d8d21f737c187f267ae31b6e6c4007ef12c6173/config/standalone-logback.xml#L21

**To Reproduce**
easy to reporduce, start pravega in standalone can reproduce it.

### PR DESCRIPTION
**Pull request by Shoothzj**
**Change log description**  
Correct the log location prompt.

**Purpose of the change**
Fixes #6803.

**How to verify it**
Launch Pravega in standalone mode, and check the `standalone.log` and the prompt.

### CODE REVIEW

**Comment by Shoothzj** [comment]
@RaulGracia PTAL

**Comment by RaulGracia** [comment]
Thanks @Shoothzj for your contribution. Before going into review process, we have some guidelines in the project to propose PRs: https://github.com/pravega/pravega/wiki/Contributing#issues-and-pull-requests

At least, I miss an issue that explains the problem this PR intents to solve. Also, while I understand that the change proposed my be difficult to test (is just the location of the log for standalone), maybe you could fill up the PR with a `How to verify` section showing the result of the change proposed while running standalone locally, as a way to validate it. Thanks!

**Comment by Shoothzj** [comment]
@RaulGracia Thanks, I created #6803 and fill the `How to verfiy` chapter. :)

**Comment by Shoothzj** [comment]
@RaulGracia PTAL

**Review by RaulGracia — APPROVED** [review]
LGTM.

**Comment by RaulGracia** [comment]
Thanks for the contribution @Shoothzj!

**Pull request merged**
