### PR TITLE
Issue 7106: Cherry-pick PR 7103 to r0.13

### PR DESCRIPTION
**Pull request by Bhupender-Y**
**Change log description**  
cherry-pick PR #7103 to r0.13

**Purpose of the change**  
#7106 

**What the code does**  
Add more logs in EventProcessorCell. It will help to identify the cause of failure if happens in any event processor. 

**How to verify it**  
N/A

### CODE REVIEW

**Review by shshashwat — APPROVED** [review]
LGTM

**Comment by RaulGracia** [comment]
@Bhupender-Y @shshashwat hi guys, just FYI: In general, in the project we reserve cherry-picks to fully validated major bugfixes that are required in previous release branches. If they are not fully validated, we may need to revert the change as recently happened with #7095, which is undesirable. While I may be wrong, this PR seems to be adding few log lines that may be useful for finding some bug in the Controller event processors. But the PR itself is not fixing anything, so I would suggest to keep this PR until the bug you may be looking for is fixed and validated, in which case it is fine to cherry pick.

**Comment by RaulGracia** [comment]
Also, I have fixed the formatting of the PR title. But, please, do it yourself as otherwise the commit message may also contain wrong formatting if the person pushing the commit button does not take proper care of it.

**Comment by Bhupender-Y** [comment]
Thanks @RaulGracia, This PR is just having extra logging only. These logs will help to debug issues in production if any issue comes up in event processor cell because of any rare case scenario.

**Review by abhinb — APPROVED** [review]
LGTM

**Pull request merged**
