### PR TITLE
Issue 6448: pravega version change to 0.10.2 on r0.10

### LINKED ISSUE #6448: Pravega version change from 0.10.2 to 0.10.2-SNPSHOT for branch r0.10
**Describe the bug**
Pravega version change from 0.10.2 to 0.10.2-SNPSHOT for branch r0.10

### PR DESCRIPTION
**Pull request by pbelgundi**
Signed-off-by: pbelgundi <prajakta.belgundi@emc.com>

**Change log description**  
Change the pravegaVersion on branch `r0.10` from `0.10.2-SNAPSHOT` to `0.10.2`

**Purpose of the change**  
Fixes #6448

### CODE REVIEW

**Review by crazyzhou — CHANGES_REQUESTED** [review]
The change is correct, but we need to change the target branch to another temporary branch creating based on `r0.10` instead of `r0.10` itself, like this one https://github.com/pravega/hadoop-connectors/pull/163
otherwise the github actions will trigger the build and publish the formal release on github registry

**Comment by pbelgundi** [comment]
> The change is correct, but we need to change the target branch to another temporary branch creating based on `r0.10` instead of `r0.10` itself, like this one [pravega/hadoop-connectors#163](https://github.com/pravega/hadoop-connectors/pull/163) otherwise the github actions will trigger the build and publish the formal release on github registry

Ok. Changed the base branch to another temporary branch.

**Review by crazyzhou — APPROVED** [review]
LGTM

**Comment by shrids** [comment]
We are not changing r0.10 branch here, could you update the the Description here?

**Comment by RaulGracia** [comment]
This PR is effectively changing the workflow defined in this Wiki (it may not have been the first one, though): https://github.com/pravega/pravega/wiki/How-to-release#bug-fix-release

My feeling is that we are silently adopting a different approach to release (i.e., changing from changing the Pravega version as a regular commit in the release branch to create a temporary branch to do exclusively that change, that will not be present in the release branch history anymore). Before we start adopting this by default, please update the Wiki page and make sure that the community acknowledges this change in release procedure (if someone just follows the Wiki, he/she will do it in the old way). cc/ @fpj @derekm

**Comment by pbelgundi** [comment]
> We are not changing r0.10 branch here, could you update the the Description here?

Updated.

**Review by shrids — APPROVED** [review]

**Pull request merged**
