### PR TITLE
Issue 2973: Update Zookeeper Docker image dependency

### LINKED ISSUE #2973: Update Zookeeper docker image
Zookeeper docker image version used for Pravega is "3.5.2 alpha". There are a huge number of bug fixes and improvements available in 3.5.3 and 3.5.4 beta releases,

Please refer https://zookeeper.apache.org/releases.html

Maybe this should be the base for Pravega also.

### PR DESCRIPTION
**Pull request by adrianmo**
**Change log description**  
Update Zookeeper Docker image dependency from `jplock/zookeeper:3.5.2-alpha` to official `zookeeper:3.5.4-beta`. Newer versions of Zookeeper contain a significant number of bug fixes. Check the following link for a detailed change log: https://zookeeper.apache.org/releases.html

**Purpose of the change**  
Fixes #2973

**What the code does**  
Update Zookeeper Docker image in compose files.

**How to verify it**  
All tests must pass.

Signed-off-by: Adrian Moreno <adrian@morenomartinez.com>

### CODE REVIEW

**Comment by fpj** [comment]
@arvindkandhare the build passed, so that's an indication that this is ok. Could we run the system tests with this patch to increase our confidence on the changes proposed here?

**Comment by adrianmo** [comment]
@fpj actually, I already run the system tests. Here's the result: https://asd-nautilus-jenkins.isus.emc.com/jenkins/view/pravega/job/pravega-branch-builder/701/

**Comment by adrianmo** [comment]
@arvindkandhare according to the official Curator documentation, Curator 4.0 is compatible with Zookeeper 3.5.x, so it should be OK to use the latest 3.5.4-beta version. Source: https://curator.apache.org/zk-compatibility.html

**Comment by arvindkandhare** [comment]
> Curator 4.0 is compatible with Zookeeper 3.5.x, so it should be OK to use the latest 3.5.4-beta version.

Thank for confirming. Approving the PR.

**Pull request merged**
