### PR TITLE
Issue 4629: Remove the inadvertantly added Swap file

### LINKED ISSUE #4629: A Swap file was inadvertantly added
**Problem description**
Upon looking for something else in the directory, I noticed that a Swap file with name `.config.properties.swp` was added by PR #4515 (by mistake) under `pravega/config`. 

**Problem location**
`/path/to/pravega/config`

**Suggestions for an improvement**
Remove the file.

### PR DESCRIPTION
**Pull request by ravisharda**
**Change log description**  
Remove the Swap file.  

**Purpose of the change**  
Fixes #4629. 

**What the code does**  
Removes the Swap file. 

**How to verify it**

### CODE REVIEW

**Comment by shrids** [comment]
can we update the .gitignore file too?

**Comment by ravisharda** [comment]
> can we update the .gitignore file too?

Sure, @shrids. Pushed the change in the latest commit.

**Comment by andreipaduroiu** [comment]
Did you actually delete the file? I don't see it in the changelist.

**Comment by ravisharda** [comment]
> Did you actually delete the file? I don't see it in the changelist.

Yes, please see `config/.config.properties.swp`.

**Pull request merged**
