### PR TITLE
Issue 5580: Reformats rollover logs filename and folder structure.

### LINKED ISSUE #5580: Ensure timestamp is included in the filename of Pravega logs during rollover
**Problem description**
At the moment Pravega logs are rolled over using the rollover policy mentioned in the logback configuration file. File name of rolled over log compressed file includes only YYYY-MM-DD.
e.g: pattern for controller is controller_2021-01-05.97.log.gz

**Problem location**
https://github.com/pravega/pravega/blob/6add9aa65dcb96337f5cb0c578f92f1d5eec2318/dist/conf/logback.xml#L24

**Suggestions for an improvement**
Filename of Pravega rolled over log compressed file should include timestamp of log when the rollover happens.

### PR DESCRIPTION
**Pull request by kotlasaicharanreddy**
**Change log description**  

Ensure timestamp is included in the filename of compressed rollover logs.

Example:
Logs are organized as below:
logs
├── 2021-02-03_05
│   ├── segmentstore_server_2021-02-03_05.0.log.gz
│   ├── segmentstore_server_2021-02-03_05.1.log.gz
│   ├── segmentstore_server_2021-02-03_05.2.log.gz
│   ├── segmentstore_server_2021-02-03_05.3.log.gz
│   └── segmentstore_server_2021-02-03_05-4.log.gz
├── 2021-02-03_06
│   ├── segmentstore_server_2021-02-03_06.0.log.gz
│   └── segmentstore_server_2021-02-03_06.1.log.gz
└── controller-server.log

**Purpose of the change**  
Fixes #5580

**What the code does** 
Adds `%d{YYYY-MM-dd, aux}` specifier in the `<fileNamePattern>` to organize compressed rollover logs into folders by date.

Adds timestamp to the filename of the compressed rollover logs and also ensures that logs are rolled over hourly and moved into its corresponding folder.

**How to verify it**  
- Timestamp should be included in the compressed rollover log filename.
- Rollover logs should be organized into folders by date.

### CODE REVIEW

**Review by shrids — APPROVED** [review]
LGTM. 
Please update the PR description with an example listing how logs would be organized inside `/opt/logs` folder of the container.

**Review by shiveshr — APPROVED** [review]

**Review by shrids — CHANGES_REQUESTED** [review]
Observing that `/opt/pravega/logs/2021-02-02/segmentstore_2021-02-02_05-15.59.log.gz` contains logs around the timestamp much greater than 05:15:00 . Perhaps we can tweak the approach to group hourly logs in a folder.

**Review by shrids — COMMENTED** [review]
LGTM.
Please update the PR description to match the new changeset and perhaps we should modify all the logback.xml to match this new configuration.

**Comment by kotlasaicharanreddy** [comment]
> Observing that `/opt/pravega/logs/2021-02-02/segmentstore_2021-02-02_05-15.59.log.gz` contains logs around the timestamp much greater than 05:15:00 . Perhaps we can tweak the approach to group hourly logs in a folder.

Tweaked as suggested and tested it thoroughly

**Review by shrids — APPROVED** [review]

**Pull request merged**
