### PR TITLE
Issue 6431: Update checkstyle

### LINKED ISSUE #6431: Update Checkstyle DOCTYPE header and checkstyleToolVersion to the latest
**Is your feature request related to a problem? Please describe.**
1. The DOCTYPE header which previously contains PuppyCrawl looks a bit fishy and not official. According to the latest doc (https://checkstyle.org/config.html#Configuration_XML_Structure), it has been updated from PuppyCrawl and CheckStyle.
2. checkstyleToolVersion is outdated. The latest release is 9.1 (https://checkstyle.sourceforge.io/releasenotes.html)

**Describe the solution you'd like**
1. In checkstyle.xml, replace ` "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
     "http://www.puppycrawl.com/dtds/configuration_1_3.dtd"` with `<!DOCTYPE module PUBLIC
  "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
  "https://checkstyle.org/dtds/configuration_1_3.dtd"`

2. In gradle.properties, update checkstyleToolVersion from 8.23 to 9.1

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jameskim0987**
**Change log description**  
Updates DOCTYPE header in checkstyle.xml and update checkstyleToolVersion from 8.23 to 9.1 (latest)

**Purpose of the change**  
Fixes #6431 

**What the code does**  
1. update DOCTYPE header in checkstyle.xml
2. update checkstyleToolVersion from 8.23 to 9.1 (latest)

**How to verify it**  
build should pass

### CODE REVIEW

**Comment by jameskim0987** [comment]
Is there a way to bypass or update the GHA build to the updated checkstyle?

**Comment by andreipaduroiu** [comment]
@jameskim0987 I'm afraid I don't understand your question. Do you want to skip checkstyle checks on GHA? That is not an option. There is a reason checkstyle is there.

Does this build pass on your local machine?

**Comment by jameskim0987** [comment]
@andreipaduroiu Yes, the build passes on my local machine.

**Comment by RaulGracia** [comment]
@jameskim0987 are you still working on this?

**Comment by jameskim0987** [comment]
@RaulGracia No, I finished working on it. It needs to be reviewed.

**Comment by RaulGracia** [comment]
@jameskim0987 the change you are proposing is breaking the build. I have tested that locally and I can confirm that it also breaks the build when running `./gradlew checkstyleMain`. The responsibility for the PR to pass the build is yours as author of the code (even though reviewers can help). So, let us know if you are still working on making the build to pass or not.

**Comment by jameskim0987** [comment]
@RaulGracia Oh I see. At the moment, I won't be working on it. I'll close the PR and re-open when I start working again.

**Pull request closed without merging**
