### PR TITLE
Issue 2515: Java serialization for `ClientConfig`, `Credentials`

### LINKED ISSUE #2515: Support Java serialization of client configuration classes
**Problem description**
It is quite handy to be able to serialize the Pravega configuration classes to accommodate the Flink connector.   In Flink, the application's `main` method uses the Flink DSL to define a job graph, which is then serialized and sent to a Flink cluster for execution.   Therefore instances of `FlinkPravegaReader` and other such connector classes implement `java.io.Serializable`, and may contain instances of Pravega configuration classes.

**Suggestions for an improvement**
- implement `java.io.Serializable` on the following:
  - `io.pravega.client.stream.impl.Credentials`
  - `io.pravega.client.ClientConfig`

See pravega/flink-connectors#48 for additional background.

### PR DESCRIPTION
**Pull request by EronWright**
Signed-off-by: Eron Wright <eronwright@gmail.com>

**Change log description**
- implements `Serializable` on `ClientConfig`, `Credentials`

**Purpose of the change**
Closes #2515 

**What the code does**
Enables serialization for client config classes for interop with Flink.

**How to verify it**
N/A

### CODE REVIEW

**Comment by andreipaduroiu** [comment]
What are some expected use cases for these configs to be serialized and deserialized?
Is it:
1. The exact same Pravega process will be serializing and deserializing them.
OR
2. (inferred from the issue) One Pravega instance serializes it, then Flink takes the (opaque) serialization and passes it to another Pravega instance?

If it's 2, then Java Serialization won't be enough, as it does not support proper versioning. You will need to write serialization code using `VersionedSerializer`, which is backwards and forwards compatible.

**Comment by tkaitchuck** [comment]
My thought was similar to Andrei's but I think that given that this is a config object, we may want to send it through a textual medium. So I think the solution is to:
1. Commit this as-is (because this is the way that the other configs work)
2. Create an issue describing how we should encode config in a textual format and manage versioning.

**Comment by EronWright** [comment]
Thanks @Tom for suggesting a staged approach which gives us parity across the configs.   

@andreipaduroiu the requirement is closer to (1) than (2) in the sense that the serialized configs will only be read by the version that created them.     The flow is:

**Comment by EronWright** [comment]
@arvindkandhare took your good advice and added a unit test.   Please take another look.

**Pull request merged**
