### PR TITLE
Issue 6796: grpcversion 1.47.0 (was 1.39.0)

### LINKED ISSUE #6796: Build fails on macOS with M1 processor
**Describe the bug**
When building on macOS, the build fails unable to find protobuf tools:

```
Execution failed for task ':shared:controller-api:generateProto'.
> Could not resolve all files for configuration ':shared:controller-api:protobufToolsLocator_grpc'.
   > Could not find protoc-gen-grpc-java-1.39.0-osx-aarch_64.exe (io.grpc:protoc-gen-grpc-java:1.39.0).
```

**To Reproduce**
Build on macOS with an M1 machine

**Additional information**
Required artifacts are found when using gRPC 1.47.0

### PR DESCRIPTION
**Pull request by cheleb**
**Change log description**
  Update grpc version to a version (latest) with ARM support.
**How to verify it**
 Build with a M1 / x64
**Purpose of the change**  
Fixes build on M1 (MacOSX)

Fixes #6796

### CODE REVIEW

**Review by derekm — APPROVED** [review]

**Comment by RaulGracia** [comment]
Thanks @cheleb for the contribution. @kotlasaicharanreddy @derekm cam we check that this dependency change does not impact on any of the downstream dependencies? (like connectors or samples)

**Comment by kotlasaicharanreddy** [comment]
@RaulGracia I've checked this with spark and flink connector jenkin jobs. Both were passed without any impact. Will approve once I test this with samples.

**Comment by shshashwat** [comment]
> @RaulGracia I've checked this with spark and flink connector jenkin jobs. Both were passed without any impact. Will approve once I test this with samples.

@kotlasaicharanreddy, Please check Schema-Registry too once

**Comment by fpj** [comment]
Hey @cheleb, thanks a lot for creating this PR and contributing, it's highly appreciated. Could you check other PRs for how we do it? We try to be thorough about it so that it is helps the reviewer understand the context and it is all properly documented. I'd also encourage you to check this guide to contributors:

https://github.com/pravega/pravega/wiki/Contributing

**Review by kotlasaicharanreddy — COMMENTED** [review]
I've verified/tested this Pravega-samples, Schema-registry and backward compatibility. 
System-tests are also green.

**Review by kotlasaicharanreddy — COMMENTED** [review]
@cheleb were you able to reproduce this consistently ? It would be helpful if you provide the grpc release docs here which states that grpcversion:1.47.0 is solving the issue.

**Review by RaulGracia — APPROVED** [review]

**Pull request merged**
