### PR TITLE
Issue 5435: Allow DefaultCredentials to be assigned to both new and legacy Credentials interface

### LINKED ISSUE #5435: Client-side code changes is required if 'DefaultCredentials' is assigned to legacy `Credentials` interface
**Problem description**
PR #5373 added support for implementations of legacy Credentials interface `io.pravega.client.stream.impl.Credentials`. However, `DefaultCredentials` remained an implementation of the new `io.pravega.shared.security.auth.Credentials` interface. As a result, existing code of the following kind will fail compilation when upgrading to `0.9.0`: 

```java
import io.pravega.client.stream.impl.Credentials;
...
....
     // Compilation will fail here upon upgrade to `0.9.0` Pravega client and requires code changes to assing
     // it to `io.pravega.shared.security.auth.Credentials` instead. 
     Credentials credentials = new DefaultCredentials(password, username); 
```

The backward compatibility promise made in PR #5373 is therefore only partial. The existing implementation allows for loading a custom implementation of `io.pravega.client.stream.impl.Credentials` interface to be loaded and used in client applications, but doesn't allow an object of that implementation to be assignable to the old interface, as shown above. This can be confusing for users. 

**Problem location**

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by ravisharda**
**Change log description**  
Make `DefaultCredentials` implement the legacy `io.pravega.client.stream.impl.Credentials` interface instead of `io.pravega.shared.security.auth.Credentials`. Since, the legacy interface, in turn, extends the new interface, `DefaultCredentials` may be assigned to both those interfaces, improving its backward compatibility. 

**Purpose of the change**  
Resolves #5435. 

**What the code does**  
* Changes the interface that `DefaultCredentials` implements from `io.pravega.shared.security.auth.Credentials` to `io.pravega.client.stream.impl.Credentials`. 

**How to verify it**  
All unit and integration tests must pass.

### CODE REVIEW

**Review by crazyzhou — APPROVED** [review]
LGTM. Just a small question to ask, how will we deal with `DefaultCredentials` class when we do the removal in 0.10? It is a little bit strange(not that much) to have this class in `io.pravega.client.stream.impl` package

**Comment by ravisharda** [comment]
@crazyzhou Yes, we should move `io.pravega.client.stream.impl.DefaultCredentials` to a better package too. 

IMO, we should do that along with the change that we do later for removing the backward compatibility with the old `Credentials` interface (#5383), so that both these related breaking changes are handled together by applications and connectors.

**Comment by RaulGracia** [comment]
Checked that previously broken applications now work with this change:
- Pravega Samples
```
λ .\gradlew.bat installDist
...
BUILD SUCCESSFUL in 13m 37s
66 actionable tasks: 66 executed
```
-  Pravega Benchmark
```
λ .\gradlew.bat installDist
...
BUILD SUCCESSFUL in 20s
5 actionable tasks: 5 executed
```
- Pravega Longevity
```
λ .\gradlew.bat build
...
BUILD SUCCESSFUL in 2m 6s
8 actionable tasks: 8 executed

**Review by RaulGracia — APPROVED** [review]

**Comment by RaulGracia** [comment]
@ravisharda I have seen 2 or 3 times in this PR the same test failing:
```
io.pravega.cli.user.kvs.SecureKVTCommandsTest > testDeleteKVT FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds
        at java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
```
Any change that this change is related to that failure? @ravisharda @anirudhkovuru

**Pull request merged**
