### PR TITLE
Issue 5686: Cherry pick PR 5652 into r0.9

### LINKED ISSUE #5686: Cherry-pick issue 5653 fix PR: 5652 into r0.9 branch
**Problem description**

Cherry pick PR #5652

**Problem location**
r0.9

**Suggestions for an improvement**
cherry-pick it PR #5652

### PR DESCRIPTION
**Pull request by shrids**
**Change log description**  

Cherry pick PR #5652

**Purpose of the change**  
Fixes #5686 

**What the code does**  
See PR #5652 

**How to verify it**  
See PR #5652

### CODE REVIEW

**Comment by sachin-j-joshi** [comment]
@shrids Codecov is complaining

**Review by sachin-j-joshi — COMMENTED** [review]
@shrids Codecov is complaining

**Comment by medvedevigorek** [comment]
The codecov shows bunch of new files and perhaps this is a reason why it thinks that overall coverage is below 80% 
https://codecov.io/gh/pravega/pravega/compare/34d8c7516d29f9a5d9de2750218bcc7680ef43a7...3673a14d1cccc982a610d123490f92ee48cb04a3/changes

@derekm, is it something you can check to see if you have any to get pass it?

**Comment by medvedevigorek** [comment]
The other observation  is that Codecov is done twice for `patch` and `project` which doesn't look normal. 

@shrids , i don't know, maybe triggering another build will help. If not then perhaps the only option is to discard that branch and re-do cherry-pick again. Thoughts?

**Comment by shrids** [comment]
Sure @medvedevigorek will try the build again, if it does not work will create a new cherry-pick branch ...

**Comment by shrids** [comment]
This PR is overriden with this PR: https://github.com/pravega/pravega/pull/5703

**Pull request closed without merging**
