### PR TITLE
Issue 7330: Update pravega dependencies version to fix the CVEs.

### PR DESCRIPTION
**Pull request by a6dulaleem**
Change log description
This PR is Upgrading the following dependencies in the pravega

Dependency | Current Version | CVE fix Version
-- | -- | --
apacheAvro | 1.11.1 | 1.11.3
jackson| 2.14.1 | 2.15.3
marathonClient | 0.6.2 | 0.6.3
netty | 4.1.94.Final | 4.1.100.Final

Purpose of the change
to fix https://github.com/pravega/pravega/issues/7330

What the code does
The code is just upgrading the version of pravega dependencies in gradle properties

How to verify it
Run the entire system test

### CODE REVIEW

**Comment by RaulGracia** [comment]
Thanks @a6dulaleem, please make sure that this change works with system tests. Also, having a performance test on this change may be also a good point (due to netty dependency change).

**Comment by a6dulaleem** [comment]
Ran a successful system test, system test number is 5286.

**Comment by a6dulaleem** [comment]
> Thanks @a6dulaleem, please make sure that this change works with system tests. Also, having a performance test on this change may be also a good point (due to netty dependency change).

Sure, will do

**Review by abhinb — APPROVED** [review]

**Review by anishakj — APPROVED** [review]
LGTM

**Review by ShwethaSNayak — APPROVED** [review]
LGTM

**Pull request merged**
