### PR TITLE
Issue 7042: Fix DataCorruptionException due to race condition in Cache

### LINKED ISSUE #6785: Apparently corrupted in-memory data read from Storage
**Describe the bug**
During fault injection testing (30% packet loss), we have found one container unable to recover. The reason for the container to recover was during tail-caching the Storage Metadata Table Segment (`SegmentId = 11`) and the problem is related to not being able to deserialize one `TableEntry`:
```
2022-06-17 09:47:55,289 126152592 [core-4] WARN  i.p.s.s.tables.ContainerKeyIndex - KeyIndex[42]: Tail-caching failed for Table Segment 11; TailCachingStartOffset=771714081, LastIndexedOffset=774186913, CurrentOffset=771714081, SegmentLength=774199051.
io.pravega.common.io.SerializationException: Read header with invalid data. KeyLength=1315272495, ValueLength=842411555
        at io.pravega.segmentstore.server.tables.EntrySerializer.validateHeader(EntrySerializer.java:187)
        at io.pravega.segmentstore.server.tables.EntrySerializer.readHeader(EntrySerializer.java:172)
```

We have done some investigation and discarded the following:
- The problem is not related with the Bookkeeper data stored in Bookkeeper and recovered during tail caching, as the first Bookkeeper entry for Table Segment 11 in container 42 has an offset higher (`773771503`) than the offset at which the serialization error is occurring:
```
container_recover_42.txt | grep -i "SegmentId = 11," | grep 771
        @[11,36]: StreamSegmentAppendOperation: SequenceNumber = 13351074, SegmentId = 11, Offset = 773771503, Length = 0, Attributes = 0.
```
- The problem does not seem to be related with the data on LTS neither. To prove that, we have downloaded the chunks for the Table Segment and we have been able to process the Table Entries of that using the Table Segment Recovery command in the CLI:
```
PARSED OPERATION AT CHUNK OFFSET 88979 WITH CONTENTS: KEY UnpooledHeapByteBuf(ridx: 0, widx: 60, cap: 60/60) KEY HASH a43b0bc5-07bd-4875-0bc8-1c481246fa1c VALUE: UnpooledHeapByteBuf(ridx: 0, widx: 388, cap: 388/388)
PARSED OPERATION AT CHUNK OFFSET 89444 WITH CONTENTS: KEY UnpooledHeapByteBuf(ridx: 0, widx: 64, cap: 64/64) KEY HASH 1983fbae-5aa3-f438-d26c-e5d195e616e6 VALUE: UnpooledHeapByteBuf(ridx: 0, widx: 83, cap: 83/83)
PARSED OPERATION AT CHUNK OFFSET 89608 WITH CONTENTS: KEY UnpooledHeapByteBuf(ridx: 0, widx: 49, cap: 49/49) KEY HASH 0744159a-5bf4-371c-b94b-b161fd7735d8 VALUE: UnpooledHeapByteBuf(ridx: 0, widx: 353, cap: 353/353)
PARSED OPERATION AT CHUNK OFFSET 90027 WITH CONTENTS: KEY UnpooledHeapByteBuf(ridx: 0, widx: 94, cap: 94/94) KEY HASH ad8a377f-b1aa-70b3-daab-bd31da9b832b VALUE: UnpooledHeapByteBuf(ridx: 0, widx: 327, cap: 327/327)
PARSED OPERATION AT CHUNK OFFSET 90465 WITH CONTENTS: KEY UnpooledHeapByteBuf(ridx: 0, widx: 102, cap: 102/102) KEY HASH 4293a33d-6426-9f73-8de0-8ce5bdc54f14 VALUE: UnpooledHeapByteBuf(ridx: 0, widx: 239, cap: 239/239)
PARSED OPERATION AT CHUNK OFFSET 90823 WITH CONTENTS: KEY UnpooledHeapByteBuf(ridx: 0, widx: 58, cap: 58/58) KEY HASH dd243ae6-df79-990e-0dab-d50bb7880aa2 VALUE: EmptyByteBufBE
PARSED OPERATION AT CHUNK OFFSET 90898 WITH CONTENTS: KEY UnpooledHeapByteBuf(ridx: 0, widx: 64, cap: 64/64) KEY HASH 1983fbae-5aa3-f438-d26c-e5d195e616e6 VALUE: EmptyByteBufBE
```

- We have also discarded that the problem is in the deserialization logic, given we have tested to use in the CLI command the same approach to deserialize TableEntries as in `ContainerKeyIndex`: `AsyncTableEntryReader.readEntryComponents(inputReader, nextOffset, serializer)`

With this, the next step has been to output the hash of the Keys in the Table Segment, both in the impacted cluster and the CLI command, which are both using the same data from LTS. This is a summary of what we have found:
```
OFFSET       CLUSTER OUTPUT KEY HASH                      TOOL OUTPUT KEY HASH
774161690    a43b0bc5-07bd-4875-0bc8-1c481246fa1c         a43b0bc5-07bd-4875-0bc8-1c481246fa1c  OK
774162155    1983fbae-5aa3-f438-d26c-e5d195e616e6         1983fbae-5aa3-f438-d26c-e5d195e616e6  OK
774162319    0744159a-5bf4-371c-b94b-b161fd7735d8         0744159a-5bf4-371c-b94b-b161fd7735d8  OK
774162738    ad8a377f-b1aa-70b3-daab-bd31da9b832b         ad8a377f-b1aa-70b3-daab-bd31da9b832b  OK
774163176    4293a33d-6426-9f73-8de0-8ce5bdc54f14         4293a33d-6426-9f73-8de0-8ce5bdc54f14  OK
774163534    2af52d84-7846-e441-c735-808d8b4a6df5         dd243ae6-df79-990e-0dab-d50bb7880aa2  WRONG!
774163609    FAILURE!                                     1983fbae-5aa3-f438-d26c-e5d195e616e6  FAILURE!
```

As visible, before the serialization problem appears, the hashes of Keys in both the impacted cluster and the local processing via CLI command match. However, the entry before the last one differs in the hash, and is in the next entry where the Table Segment recovery process hits the serialization exception.

To further understand that, we have printed the actual byte contents of keys both locally reading from the chunks and in the impacted cluster, and we can see the reason for the hash to be different in the entry before the last one:

```
OUTPUT FROM IMPACTED CLUSTER
----------------------------
i.p.s.s.tables.ContainerKeyIndex - KeyIndex[42]: Attempting to deserialize table entry at 774163534.
2022-06-23 13:01:25,934 19631 [core-18] INFO  i.p.s.s.tables.ContainerKeyIndex - KeyIndex[42]: Correctly deserialized entry io.pravega.segmentstore.server.tables.AsyncTableEntryReader$DeserializedEntry@5b532267 with hash 2af52d84-7846-e441-c735-808d8b4a6df5.
2022-06-23 13:01:25,934 19631 [core-18] INFO  i.p.s.s.tables.ContainerKeyIndex - KeyIndex[42]: Deserialized entry info: Key io.pravega.common.util.CompositeBufferView@b9b15eb7 key content {108,111,110,103,101,118,105,116,121,47,109,101,100,105,117,109,83,99,97,108,101,78,101,119,47,50,54,46,35,101,112,111,99,104,46,49,50,36,97,116,116,114,105,98,117,116,101,115,46,105,110,100,101,109,83,99,97,108}, Value null, Version 774163534, KeyLength 58, KeyOffset 17, EntryVersion -9223372036854775808, ValueLength -1, TotalLength 75, isDeletion true

OUTPUT FROM CLI TOOL
--------------------
Deserialized entry info: Key {108,111,110,103,101,118,105,116,121,47,109,101,100,105,117,109,83,99,97,108,101,78,101,119,47,50,54,46,35,101,112,111,99,104,46,49,50,36,97,116,116,114,105,98,117,116,101,115,46,105,110,100,101,120,46,66,45,48}, Value null, Version 90823, KeyLength 58, KeyOffset 17, EntryVersion -9223372036854775808, ValueLength -1, TotalLength 75, isDeletion true
empty one
PARSED OPERATION AT CHUNK OFFSET 90823 WITH CONTENTS: KEY UnpooledHeapByteBuf(ridx: 0, widx: 58, cap: 58/58) KEY HASH dd243ae6-df79-990e-0dab-d50bb7880aa2 VALUE: EmptyByteBufBE
```

As you can see, all the fields related to the Table Segment header information are the same, but the actual payload of the Key changes in the last 5 bytes:
```
{108,111,110,103,101,118,105,116,121,47,109,101,100,105,117,109,83,99,97,108,101,78,101,119,47,50,54,46,35,101,112,111,99,104,46,49,50,36,97,116,116,114,105,98,117,116,101,115,46,105,110,100,101,109,83,99,97,108}
vs
{108,111,110,103,101,118,105,116,121,47,109,101,100,105,117,109,83,99,97,108,101,78,101,119,47,50,54,46,35,101,112,111,99,104,46,49,50,36,97,116,116,114,105,98,117,116,101,115,46,105,110,100,101,120,46,66,45,48}
```
This explains why the hash is different. Also, the corruption that appears to begin at the end of the Key content seems to continue, as the next entry is impacted also in the header.

Given that the data being used is the same in both the CLI command and the impacted cluster, as well as the serialization, the remaining culprits for this problem may be related on how the data is read to be deserialized later on. Initially, the following elements are used for reading only during Table Segment recovery in the cluster are:
- `StreamSegmentReadIndex` / `DirectMemoryCache` that manage and store data in memory.
-  `AsyncReadResultProcessor`  to provide the contents of entries for being deserialized.

We need to continue investigating to get to the bottom of this.

**To Reproduce**
Very hard, only faced this once.

**Screenshots**
n/a

**Additional information**
n/a

### LINKED ISSUE #7042: Handle DataCorruptioException in Segment Stores
**Describe the bug**
Sometimes the `DataCorruptionException` has been observed in the Segment Stores when running Pravega with low resources and heavy loads.

**To Reproduce**
Start Pravega with low resources
Start a heavy load
Keep a watch on segment stores :- It might fill up the entire cache and `DataCorruptionException` will be observed

**Additional information**
Inside of `StreamSegmentReadIndex` it is attempting to do some VERY sophisticated synchronization which is critical to get right to prevent this sort of error.

### PR DESCRIPTION
**Pull request by shshashwat**
**Change log description**  
The changes are to put a synchronization block in the `StreamSegmentReadIndex` for `cacheStorage`. This needs to be done for every update, write, append operations.

**Purpose of the change**  
Fixes #7042 
Fixes #6785

**What the code does**  
Inside of `StreamSegmentReadIndex` it is attempting to do some sophisticated synchronization which is critical to get right to prevent this sort of error. In particular the `cacheStorage` member is accessed both inside and outside of a lock. In order to do this, it is using some double checked operations so as to not always hold a lock when accessing the data-structure. In particular when `addToCacheAndIndex` is invoked there could be a concurrent `insertEntriesToCacheAndIndex` and the append which is calling it. There will be some race between the two. The subsequent apply which invokes `appendSingleEntryToCacheAndIndex` to do the actual insert and update of the index entries.
In order to prevent this, the lock should be added to every update operations to this data structure.

**How to verify it**  
All existing test cases should pass
`DataCorruptionException` should not occur

### CODE REVIEW

**Review by tkaitchuck — COMMENTED** [review]
This change looks good. Please get in shape to be merged.

**Comment by shshashwat** [comment]
> This change looks good. Please get in shape to be merged.

Changes done, can be reviewed now

**Review by RaulGracia — CHANGES_REQUESTED** [review]
I have few questions about this change:
1. You need to provide more details in the issue about the type of data corruption that has been detected. Is the issue related to an integrity problem in the `indexEntries` data structure or internally within the `cacheStorage`?
2. The implementation of `CacheStorage` being used is `DirectMemoryCache`, which is tagged as `@ThreadSafe`. Can you detail exactly why adding an outer lock to that thread-safe object is actually solving the problem? Perhaps, a more detailed description of the race condition can help us to better understand the goal of the change.
3. We need a test to reproduce the original race condition that can verify that the proposed change actually solves it. I would not like the idea of modifying such a critical class without proper testing of the changes added.
4. What is the potential cost of this lock? Has there been any read performance test to validate that the change does not introduce a significant read performance regression?

Also, please set a more descriptive issue and PR title, as the current one seems too generic.

**Comment by shshashwat** [comment]
> I have few questions about this change:
> 
> 1. You need to provide more details in the issue about the type of data corruption that has been detected. Is the issue related to an integrity problem in the `indexEntries` data structure or internally within the `cacheStorage`?
> 2. The implementation of `CacheStorage` being used is `DirectMemoryCache`, which is tagged as `@ThreadSafe`. Can you detail exactly why adding an outer lock to that thread-safe object is actually solving the problem? Perhaps, a more detailed description of the race condition can help us to better understand the goal of the change.
> 3. We need a test to reproduce the original race condition that can verify that the proposed change actually solves it. I would not like the idea of modifying such a critical class without proper testing of the changes added.
> 4. What is the potential cost of this lock? Has there been any read performance test to validate that the change does not introduce a significant read performance regression?
> 
> Also, please set a more descriptive issue and PR title, as the current one seems too generic.

1. The issue found was with the `cacheStorage`
2. The annotation `@ThreadSafe` doesn't make the class thread safe but it's mainly for the maintainers and developers to notify them that it's thread safe and multiple threads can be allowed to access. 
3. We have reproduced this multiple times and after adding this, we are now not seeing that exception
4. Performance runs have been triggered several times in order to test if this additional lock has any effect or not. It has been observed that there is no negative impact on the performance.

**Comment by RaulGracia** [comment]
Thanks @shshashwat, let me comment on that:

> The annotation @ThreadSafe doesn't make the class thread safe but it's mainly for the maintainers and developers to notify them that it's thread safe and multiple threads can be allowed to access.

This is blatantly obvious, so maybe I did not get my point across correctly. The point is that `DirectMemoryCache` is supposedly thread-safe (and therefore, it is tagged as `@ThreadSafe`). If you look at the implementation of that class, it uses locks on the mutable data structures. Therefore, the question is what exactly is causing the data corruption here? What is the external access pattern from `StreamSegmentReadIndex` that precisely induces the race condition? Is this a synchronization problem of `StreamSegmentReadIndex` or of `DirectMemoryCache` that may not be honoring thread-safety? 

> We have reproduced this multiple times and after adding this, we are now not seeing that exception

This is a good indication, but we need a unit tests that reproduces the problem and validates the fix. This will help us to get to the next step in understanding the nature of the race condition here.

> Performance runs have been triggered several times in order to test if this additional lock has any effect or not. It has been observed that there is no negative impact on the performance.

Ok, I will probably ask for details of these experiments directly to you.

**Comment by RaulGracia** [comment]
By the way, this looks related to this issue which appeared very rarely, and we found it to be related in how the data was copied from the cache: https://github.com/pravega/pravega/issues/6785. I think this PR may be fixing that issue as well.

**Comment by RaulGracia** [comment]
Given a conversation with @tkaitchuck, looks like it is preferable to go with this fix that has been "empirically" validated until now, rather than wait for longer to improve some aspects of the PR. In this sense, I'm giving my approval to merge conditional to create a new issue with the technical debt of this PR: i) find a unit test that reproduces the issue and validates the fix, ii) revisit whether this fix should be located at the Cache level rather than at the `StreamSegmentReadIndex` level.

**Review by RaulGracia — APPROVED** [review]

**Pull request merged**
