### PR TITLE
Issue 5627: Speed up RestoreBackUpDataRecoveryTest

### LINKED ISSUE #5627: Speed up RestoreBackUpDataRecoveryTest
**Problem description**
```
Class io.pravega.test.integration.RestoreBackUpDataRecoveryTest

testDurableDataLogFailRecoveryMultipleContainers  | 39.893s | passed
testDurableDataLogFailRecoveryReadersPaused       | 39.879s | passed
testDurableDataLogFailRecoverySingleContainer     | 35.809s | passed
testDurableDataLogFailRecoveryTransactionalWriter | 36.279s | passed
testDurableDataLogFailRecoveryWatermarking        | 37.270s | passed


```

**Problem location**
io.pravega.test.integration.RestoreBackUpDataRecoveryTest

**Suggestions for an improvement**
1. Speed tests up.
2. Do not use Bookkeeper for Tier 1. Use InMemoryDurableDataLog (as long as you keep references to the factory, it will preserve data between runs - if that's what you wish). Using BK also prevents us from running the tests in parallel.

### PR DESCRIPTION
**Pull request by ManishKumarKeshri**
**Change log description**  
`FlushToStorage` is parallelized for multiple containers to flush in parallel.
 Using `InMemoryDurableDataLog`.

**Purpose of the change**  
Fixes #5627 

**What the code does**  
Improves test time of execution.

**How to verify it**  
Time should be reduced.

### CODE REVIEW

**Comment by ManishKumarKeshri** [comment]
@andreipaduroiu. Please let me know if you have any more suggestions. 
Using InMemoryDurableDataLog.

**Review by andreipaduroiu — APPROVED** [review]

**Comment by andreipaduroiu** [comment]
The changes look good, but I don't see the integration tests running any faster than they do for a master build. They still took around 21 minutes (give or take a few seconds).

**Comment by RaulGracia** [comment]
@ManishKumarKeshri there are conflicts with your other PR, please solve them. Also, can you elaborate about the following: 
i) Is it safe to use `InMemoryDurableDataLog` instead of `BookkeeperLog` to speed up things? Is this change going to make us unaware of any issue in the recovery process when Bookkeeper is involved?
ii) Can you give a sense of how much has this PR shortened the execution time of the test?

**Comment by ManishKumarKeshri** [comment]
1) Tried running the tests multiple times. And I don't think `InMemoryDurableDataLog` will cause any problem. We are already using `InMemoryStorage` for LTS.
2) Average time taken now is 117s, and previously, it was 160s. Average of 3 runs. This is the collective average time taken by all 5 tests in `RestoreBackUpDataRecoveryTest`. Actually, we start and close pravega (BK/ZK + SS + Controller) 10 times (2 times in each test) here. Each start and close of pravega takes 7.7s, so around 77s is used up here.

**Pull request merged**
