### PR TITLE
Issue 6495: DataFrameReader does not allow to read a corrupted log in BookkeeperLog repair command

### LINKED ISSUE #6495: DataFrameReader does not allow to read a corrupted log in BookkeeperLog repair command
**Describe the bug**
BookkeeperLog Repair command contributed in #6413 uses the `DebugRecoveryProcessor` to read from logs and manipulate them. However, as this class is using `DataFrameReader` as a regular recovery, it is subject to the same preconditions. Thus, if we are manipulating a log that has a duplicate entry, we will not be able to create the backup log because `DataFrameReader` throws `DataCorruptionException` when finding a duplicate entry.

We need to allow these constraints to hold or not, depending on our needs from a CLI perspective.

**To Reproduce**
Try to repair a log with an actual data corruption.

**Screenshots**
n/a

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by anirudhkovuru**
**Change log description**  
Added a new implementation of `performRecovery` in the `RecoveryProcessor` to make sure that when called there is the option to have any `DataCorruptionException` be logged or thrown back.

**Purpose of the change**  
Fixes #6495 

**What the code does**  
- Added a new method `performRecovery(boolean alertDataCorruption)` that logs the exception when called with `false` and throws the exception when called with `true`.
- Updated the `recoverAllOperations` method to have a boolean argument `alertDataCorruption`. The boolean determines if the caught `DataCorruptionException` should be logged or not.
- The existing `performRecovery` method now calls the new method with the boolean set as `true` to retain old behavior.
- The commands in the CLI using this function have been changed to use the new method with the boolean set to `false`, thereby logging the exception.

**How to verify it**  
All tests should pass.

### CODE REVIEW

**Comment by tkaitchuck** [comment]
If a serious exception is being caught and is being handled and mitigated, the proper policy is to log at `warn` level rather than at `error`

**Comment by RaulGracia** [comment]
@anirudhkovuru I have tested this change with a real Bookkeeper Log with duplicate entries, and it seems that the commands that should be tolerating data corruption exceptions are not doing it:
```
container recover 40
...
Begin DataFrame: Sequence = 8589937636, LedgerId = 697, EntryId = 3044.
        @[11,98]: UpdateAttributesOperation: SequenceNumber = 5112, SegmentId = 11, Attributes = 2.
End DataFrame: Length=98/109.

Recovery FAILED: 204 DataFrame(s) containing 222 Operation(s) were able to be recovered.
io.pravega.segmentstore.server.DataCorruptionException: Invalid Operation Sequence Number. Expected: larger than 5112, found: 5109.
        at io.pravega.segmentstore.server.logs.DataFrameReader.getNext(DataFrameReader.java:102)
        at io.pravega.segmentstore.server.logs.RecoveryProcessor.recoverAllOperations(RecoveryProcessor.java:184)
```

**Review by RaulGracia — CHANGES_REQUESTED** [review]
Tests are missing for this PR. I have also tested it on a real cluster with duplicate data frames and the current approach still induces throwing DataCorruptionException to the caller.

**Comment by RaulGracia** [comment]
Superseded by #6681.

**Pull request closed without merging**
