### PR TITLE
Issue 6682: Bump up versions of third party libraries

### LINKED ISSUE #6682: Update versions of third party dependencies
**Describe the bug**
Update the following third party dependencies in order to address vulnerabilities(CVEs). 

| Library | Current Version | 
| --- | --- | 
hadoop | 3.3.1 |
jerseyVersion| 2.29 |
com.fasterxml.jackson.core | 2.12.6 | 
junit | 4.13.1 | 
nettyVersion | 4.1.65.Final |
nettyBoringSSLVersion | 2.0.39.Final |

**Problem location**
`gradle.properties`

**Solution**
Bump up the above libraries to higher versions.

### PR DESCRIPTION
**Pull request by kotlasaicharanreddy**
Signed-off-by: kotlasaicharanreddy <kotlasaicharan@yahoo.com>

**Change log description**  
Bumps up the following libraries to higher versions to fix CVEs found.

| Library | Current Version | Updated Version |
| --- | --- | --- |
hadoop | 3.3.1 | 3.3.2 |
jerseyVersion | 2.29 | 2.35
com.fasterxml.jackson.core | 2.12.6 | 2.13.2.2
junit | 4.13.1 | 4.13.2
nettyVersion | 4.1.65.Final | 4.1.73.Final
nettyBoringSSLVersion | 2.0.39.Final | 2.0.48.Final
protobufProtocVersion | 3.14.0 | 3.19.4
bouncyCastleVersion | 1.69 | 1.70

**Purpose of the change**  
Fixes #6682 

**What the code does**  
Bumps up libraries to higher versions.

**How to verify it**  
All tests must pass.

Following tests and compatibility have been done.
- System tests TPC: 4467 is successful.
- System tests TPC#1: 2094 is successful.
- Pravega-Flink-Connector Job: 200 is successful.
- Pravega-Spark-Connector Job: 49 is successful. 
- Pravega-Samples are also compatible with these changes.

### CODE REVIEW

**Comment by shshashwat** [comment]
@kotlasaicharanreddy, could you please update the system test results here with build no?

**Review by crazyzhou — APPROVED** [review]
We have updated the Flink connector as this PR: https://github.com/pravega/flink-connectors/pull/672 and tested with this branch. All the tests can pass.

Once the pull request is merged and cherry-pick into `r0.11` branch, we will upgrade the Pravega client dependency in Flink connector in this pull request.

There is still one problem that I cannot get the correct Pravega dependency in 0.11 as we have entered the release cycle and the version is always 0.11.0 in that branch.

**Comment by kotlasaicharanreddy** [comment]
> @kotlasaicharanreddy, could you please update the system test results here with build no?

@shshashwat I've added it in the PR description itself.

**Review by RaulGracia — CHANGES_REQUESTED** [review]
There are more changes needed, at least (but maybe not only):
- Bouncycastle version to 1.71
- jacksonVersion version to 2.13.2.2
- protobufProtocVersion version to 3.19.4?

**Comment by shshashwat** [comment]
@kotlasaicharanreddy , after the commit for jackson, bouncycastle, micrometer, protobuf version changes we will need to run system tests again before merge.

**Comment by kotlasaicharanreddy** [comment]
> @kotlasaicharanreddy , after the commit for jackson, bouncycastle, micrometer, protobuf version changes we will need to run system tests again before merge.

Yes @shshashwat I've ran them again. TPC #4467 is the latest system run id.

**Review by shshashwat — APPROVED** [review]
LGTM

**Comment by kotlasaicharanreddy** [comment]
> There are more changes needed, at least (but maybe not only):
> 
> * Bouncycastle version to 1.71
> * jacksonVersion version to 2.13.2.2
> * protobufProtocVersion version to 3.19.4?

Yes @RaulGracia these are added to the changes as well.

**Review by RaulGracia — APPROVED** [review]

**Pull request merged**
