### PR TITLE
Issue 6727: Upgrade Pravega to Bookkeeper 4.15

### LINKED ISSUE #6727: Upgrade to Bookkeeper 4.15
**Describe the bug**
Bookkeeper 4.15 has significant improvements and bugfixes. We need to upgrade Bookkeeper version.

**To Reproduce**
n/a

**Screenshots**
n/a

**Additional information**
n/a

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**  
Upgrades Pravega to latest Bookkeeper version (4.15).

**Purpose of the change**  
Fixes #6727.

**What the code does**  
- Upgrades Bookkeeper dependency to 4.15.0.
-  Refactors Bookie instantiation in `BookkeeperServiceRunner` due to changes in constructor signature.
- Sets a reasonable default to User TCP timeout for non-responsive TCP connections (10 seconds), as it is available in 4.15.0 with this PR https://github.com/apache/bookkeeper/pull/2761.
- Upgrades `nettyVersion` and `nettyBoringSSLVersion` to prevent dependency conflict.
 
**How to verify it**  
Build is passing. Performance tests done with this branch.
System tests have passed with this PR test-pravega-continuous-1/2139 (using new Bookkeeper server). 
Pravega longevity also passed (pravega-longevity/1102).

### CODE REVIEW

**Comment by RaulGracia** [comment]
@eolivelli system tests are passing with these changes to upgrade to Bookkeeper 4.15. We can keep this branch open until there is a final release for Bookkeeper.

**Review by tkaitchuck — COMMENTED** [review]
LGTM

**Comment by RaulGracia** [comment]
Looks like there is some problems with either the (Netty) dependency changes in the new Bookkeeper RC or with the recent changes in Pravega dependencies:
```
io.pravega.segmentstore.server.host.ExtendedS3IntegrationTest > testFlushToStorageWithChunkedStorage FAILED
    java.lang.NoSuchMethodError: 'long io.netty.util.internal.PlatformDependent.estimateMaxDirectMemory()'
        at org.apache.bookkeeper.bookie.IndexInMemPageMgr.<init>(IndexInMemPageMgr.java:355)
        at org.apache.bookkeeper.bookie.LedgerCacheImpl.<init>(LedgerCacheImpl.java:62)
```

**Review by sachin-j-joshi — APPROVED** [review]
Looks okay to me

**Review by tkaitchuck — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

is there anything that prevent us from merging this patch ?

**Review by sachin-j-joshi — COMMENTED** [review]
Please ignore comment.
Commented on this PR instead of https://github.com/pravega/pravega/pull/6879#pullrequestreview-1109716355. 
Thanks

**Pull request merged**
