### PR TITLE
Issue 5846: Create exception to force Segment Container shutdown

### LINKED ISSUE #5846: Create exception to force Segment Container shutdown
**Describe the solution you'd like**
Currently we overload the `DataCorruptionException` with situations that are not even remotely connected to data corruption (i.e., cache full). This causes unwanted confusion when parsing logs and trying to root cause problems.

**Solutions**
1. Create a new exception (`ServiceHaltException` which inherits from `StreamingException`),
2. Make `DataCorruptionException` extend from it. This means the `ServiceHaltException` may need to have the same constructor(s) as `DataCorruptionException`.
3. Look through the codebase where `DataCorruptionException` is thrown where **it does not indicate data corruption**. For example, a cache full exception is not a data corruption. Replace those usages with `ServiceHaltException`
3.  wire it to auto-shut down the Segment Container, DurableLog and StorageWriter and replace usages of `DataCorruptionException` with this one where appropriate.
4. Look for `instanceof DataCorruptionException` - some of these (but **not all**) will trigger various components to shut down. In these cases, replace it with `instanceof ServiceHaltException` (and optionally add a comment indicating it also covers DCE).
5. Optional: in `OperationProcessor.java#processCommits`, in the `isFatalException`, consider actually throwing the exception as well (after invoking callbacks) - this should force the commit processor to stop immediately and not log additional noise in the logs.

When this is done, `DataCorruptionException` should ONLY be used in those cases where data corruption is either suspected or has been confirmed.

### PR DESCRIPTION
**Pull request by ManishKumarKeshri**
**Change log description**  
Replaced `DataCorruptionException` with `ServiceHaltException` in required places:

**Purpose of the change**  
Fixes #5846 

**What the code does**  
Created a new exception `ServiceHaltException` which inherits from `StreamingException`. Made `DataCorruptionException` extend from it. Replaced `DataCorruptionException` with `ServiceHaltException` in required places.

**How to verify it**  
Build shall pass.

### CODE REVIEW

**Comment by RaulGracia** [comment]
@ManishKumarKeshri codecov seems to be reporting correctly, but your change does not meet the coverage check. Please, add the necessary test coverage to have this check passing.

**Comment by ManishKumarKeshri** [comment]
HI @RaulGracia , Based on code coverage report, can you suggest on improving the coverage of DebugRecoveryProcessor -> recoverOperation or any other files. https://app.codecov.io/gh/pravega/pravega/compare/5952/diff

**Review by andreipaduroiu — APPROVED** [review]

**Comment by andreipaduroiu** [comment]
I have reviewed this PR and approved the changes. However due to their nature, these lines of code are very hard to reach in a deterministic manner (using unit tests) - they are usually the last line of defense in case we really could not figure out why we ended up in a bad situation and hence prefer to shut down vs continuing. 

I do not know how to add more unit tests to cover these - if it were easy, they would likely have already been covered. 

@fpj would you be willing to make an exception for this PR and merge it in with low code coverage? Feel free to inspect the report (linked in a CodeCov comment above) and see the comments around the lines of code touched. We literally changed `DataCorruptionException` to `ServiceHaltException` and did not alter anything in the functioning of the system.

**Comment by RaulGracia** [comment]
@fpj can you advise whether we can merge this PR or not (due to the issue with codecov)?

**Pull request merged**
